//------------------------------------------------------------------------------
// <auto-generated>
//   This file is generated by EntityTemplate.Tests.tt
//   Do not modify directly.
//
//   Regenerate via IDE (Run Custom Tool) or:
//     dotnet tool install -g dotnet-t4
//     t4 EntityTemplate.Tests.tt
//
//   Deliberately no timestamp: regeneration must be diff-clean.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable RedundantCast

namespace fennecs.tests.Templates;

/// <summary>
/// Generated EntityTemplate battery: arity 1 (TplA).
/// </summary>
public class EntityTemplate1Tests
{
    private static EntityTemplate<TplA> Template(World world) => world.Template().Needs<TplA>();


    [Fact]
    public void Single_Spawn_Provides_Required_Values()
    {
        using var world = new World();
        using var template = Template(world);

        var entity = template.Spawn(TplA.New(0));

        Assert.True(entity.Alive);
        Assert.Equal(TplA.New(0), entity.Ref<TplA>());
    }


    [Fact]
    public void Uniform_Bulk_Spawn_Shares_Values()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Same(template, template.Spawn(5, TplA.New(1)));
        Assert.Equal(5, world.Count);
        foreach (var entity in world)
        {
            Assert.Equal(TplA.New(1), entity.Ref<TplA>());
        }

        // zero and negative counts spawn nothing
        template.Spawn(0, TplA.New(9));
        template.Spawn(-3, TplA.New(9));
        Assert.Equal(5, world.Count);
    }


    [Fact]
    public void Uniform_Span_Spawn_Delivers_Handles()
    {
        using var world = new World();
        using var template = Template(world);

        var wave = new Entity[4];
        Assert.Same(template, template.Spawn(wave, TplA.New(2)));

        foreach (var entity in wave)
        {
            Assert.True(entity.Alive);
            Assert.Equal(TplA.New(2), entity.Ref<TplA>());
        }

        // empty destination spawns nothing
        template.Spawn(Span<Entity>.Empty, TplA.New(9));
        Assert.Equal(4, world.Count);
    }


    [Fact]
    public void Factory_Spawn_Provides_Per_Entity_Values()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Same(template, template.Spawn(7, i => TplA.New(i)));
        Assert.Equal(7, world.Count);

        var seen = new HashSet<int>();
        foreach (var entity in world)
        {
            var index = entity.Ref<TplA>().Value;
            Assert.True(seen.Add(index));
        }
        Assert.Equal(Enumerable.Range(0, 7).ToHashSet(), seen);

        // zero count spawns nothing, null factory throws
        template.Spawn(0, i => TplA.New(i));
        Assert.Equal(7, world.Count);
        Assert.Throws<ArgumentNullException>(() => template.Spawn(5, (Func<int, TplA>)null!));
    }


    [Fact]
    public void Factory_Span_Spawn_Delivers_Handles()
    {
        using var world = new World();
        using var template = Template(world);

        var wave = new Entity[6];
        Assert.Same(template, template.Spawn(wave, i => TplA.New(i)));

        for (var i = 0; i < wave.Length; i++)
        {
            Assert.Equal(TplA.New(i), wave[i].Ref<TplA>());
        }

        // empty destination spawns nothing, null factory throws
        template.Spawn(Span<Entity>.Empty, i => TplA.New(i));
        Assert.Equal(6, world.Count);
        Assert.Throws<ArgumentNullException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, (Func<int, TplA>)null!);
        });
    }


    [Fact]
    public void Span_Parallel_Spawn_Blits_Per_Entity_Values()
    {
        using var world = new World();
        using var template = Template(world);

        const int count = 5;
        var values0 = new TplA[count];
        for (var i = 0; i < count; i++)
        {
            values0[i] = TplA.New(i * 10 + 0);
        }

        var wave = new Entity[count];
        Assert.Same(template, template.Spawn(wave, values0));

        for (var i = 0; i < count; i++)
        {
            Assert.Equal(values0[i], wave[i].Ref<TplA>());
        }

        // empty destination with empty values spawns nothing
        template.Spawn(Span<Entity>.Empty, Array.Empty<TplA>());
        Assert.Equal(count, world.Count);
    }


    [Fact]
    public void Span_Parallel_Spawn_Rejects_Mismatched_Lengths()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[2]);
        });

        Assert.Equal(0, world.Count);
    }


    [Fact]
    public void Add_Variants_Bake_Into_Template()
    {
        using var world = new World();
        var target = world.Spawn();
        var other = world.Spawn();
        var linked = BakedLink.New(7);

        using var template = Template(world)
            .Add(BakedVal.New(1))          // Add<T>(T)
            .Add(BakedVal.New(2))          // replaces the existing value
            .Add<BakedTag>()               // Add<C>() default
            .Add<BakedRel>(target)         // Add<T>(Entity) newable relation
            .Add(BakedRel.New(3), other)   // Add<R>(R, Entity) valued relation
            .Add(Link.With(linked));       // Add<T>(Link<T>) object link

        var entity = template.Spawn(TplA.New(0));

        Assert.Equal(BakedVal.New(2), entity.Ref<BakedVal>());
        Assert.True(entity.Has<BakedTag>());
        Assert.True(entity.Has<BakedRel>(target));
        Assert.True(entity.Has<BakedRel>(other));
        Assert.True(entity.Has(Link.With(linked)));
    }


    [Fact]
    public void Remove_Variants_Unbake_From_Template()
    {
        using var world = new World();
        var target = world.Spawn();
        var linked = BakedLink.New(7);
        var linked2 = BakedLink.New(8);

        using var template = Template(world)
            .Add(BakedVal.New(1))
            .Add<BakedTag>()
            .Add(BakedRel.New(3), target)
            .Add(Link.With(linked))
            .Add(Link.With(linked2))
            .Remove<BakedVal>()            // Remove<T>()
            .Remove<BakedRel>(target)      // Remove<T>(Entity)
            .Remove(linked)                // Remove<L>(L)
            .Remove(Link.With(linked2));   // Remove<L>(Link<L>)

        var entity = template.Spawn(TplA.New(0));

        Assert.False(entity.Has<BakedVal>());
        Assert.True(entity.Has<BakedTag>()); // untouched survivor
        Assert.False(entity.Has<BakedRel>(target));
        Assert.False(entity.Has(Link.With(linked)));
        Assert.False(entity.Has(Link.With(linked2)));
    }


    [Fact]
    public void Required_Components_Cannot_Be_Added_Or_Removed()
    {
        using var world = new World();
        using var template = Template(world);
        Assert.Throws<InvalidOperationException>(() => template.Add(TplA.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplA>());
    }


    [Fact]
    public void Needs_Widens_With_Relation_Requirement()
    {
        using var world = new World();
        var target = world.Spawn();

        using var template = Template(world).Needs<BakedRel>(target); // target baked, value per-spawn
        var entity = template.Spawn(TplA.New(0), BakedRel.New(9));

        Assert.True(entity.Has<BakedRel>(target));
        Assert.Equal(BakedRel.New(9), entity.Ref<BakedRel>(Match.Relation(target)));
    }


    [Fact]
    public void Needs_Conflicts_Throw()
    {
        using var world = new World();

        // duplicate requirement
        using var template = Template(world);
        Assert.Throws<InvalidOperationException>(() => template.Needs<TplA>());

        // requirement of an already-baked component
        using var baked = Template(world).Add(BakedVal.New(1));
        Assert.Throws<InvalidOperationException>(() => baked.Needs<BakedVal>());
    }


    [Fact]
    public void Consumed_Template_Is_Inert()
    {
        using var world = new World();

        var narrow = Template(world);
        using var wide = narrow.Needs<BakedVal>();

        narrow.Dispose(); // no-op, ownership moved on
        narrow.Dispose();
        Assert.Throws<ObjectDisposedException>(() => narrow.Add<BakedTag>());
        Assert.Throws<ObjectDisposedException>(() => narrow.Spawn(TplA.New(0)));

        // the wide template inherited the state and works
        var entity = wide.Spawn(TplA.New(1), BakedVal.New(42));
        Assert.Equal(BakedVal.New(42), entity.Ref<BakedVal>());
        Assert.Equal(TplA.New(1), entity.Ref<TplA>());
    }


    [Fact]
    public void Dispose_Semantics()
    {
        using var world = new World();

        var template = Template(world);
        template.Dispose();

        Assert.Throws<ObjectDisposedException>(() => template.Dispose());
        Assert.Throws<ObjectDisposedException>(() => template.Add(BakedVal.New(1)));
        Assert.Throws<ObjectDisposedException>(() => template.Spawn(TplA.New(0)));
    }
}

/// <summary>
/// Generated EntityTemplate battery: arity 2 (TplA, TplB).
/// </summary>
public class EntityTemplate2Tests
{
    private static EntityTemplate<TplA, TplB> Template(World world) => world.Template().Needs<TplA>().Needs<TplB>();


    [Fact]
    public void Single_Spawn_Provides_Required_Values()
    {
        using var world = new World();
        using var template = Template(world);

        var entity = template.Spawn(TplA.New(0), TplB.New(10));

        Assert.True(entity.Alive);
        Assert.Equal(TplA.New(0), entity.Ref<TplA>());
        Assert.Equal(TplB.New(10), entity.Ref<TplB>());
    }


    [Fact]
    public void Uniform_Bulk_Spawn_Shares_Values()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Same(template, template.Spawn(5, TplA.New(1), TplB.New(2)));
        Assert.Equal(5, world.Count);
        foreach (var entity in world)
        {
            Assert.Equal(TplA.New(1), entity.Ref<TplA>());
            Assert.Equal(TplB.New(2), entity.Ref<TplB>());
        }

        // zero and negative counts spawn nothing
        template.Spawn(0, TplA.New(9), TplB.New(9));
        template.Spawn(-3, TplA.New(9), TplB.New(9));
        Assert.Equal(5, world.Count);
    }


    [Fact]
    public void Uniform_Span_Spawn_Delivers_Handles()
    {
        using var world = new World();
        using var template = Template(world);

        var wave = new Entity[4];
        Assert.Same(template, template.Spawn(wave, TplA.New(2), TplB.New(3)));

        foreach (var entity in wave)
        {
            Assert.True(entity.Alive);
            Assert.Equal(TplA.New(2), entity.Ref<TplA>());
            Assert.Equal(TplB.New(3), entity.Ref<TplB>());
        }

        // empty destination spawns nothing
        template.Spawn(Span<Entity>.Empty, TplA.New(9), TplB.New(9));
        Assert.Equal(4, world.Count);
    }


    [Fact]
    public void Factory_Spawn_Provides_Per_Entity_Values()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Same(template, template.Spawn(7, i => (TplA.New(i), TplB.New(i + 1))));
        Assert.Equal(7, world.Count);

        var seen = new HashSet<int>();
        foreach (var entity in world)
        {
            var index = entity.Ref<TplA>().Value;
            Assert.True(seen.Add(index));
            Assert.Equal(TplB.New(index + 1), entity.Ref<TplB>());
        }
        Assert.Equal(Enumerable.Range(0, 7).ToHashSet(), seen);

        // zero count spawns nothing, null factory throws
        template.Spawn(0, i => (TplA.New(i), TplB.New(i + 1)));
        Assert.Equal(7, world.Count);
        Assert.Throws<ArgumentNullException>(() => template.Spawn(5, (Func<int, (TplA, TplB)>)null!));
    }


    [Fact]
    public void Factory_Span_Spawn_Delivers_Handles()
    {
        using var world = new World();
        using var template = Template(world);

        var wave = new Entity[6];
        Assert.Same(template, template.Spawn(wave, i => (TplA.New(i), TplB.New(i + 1))));

        for (var i = 0; i < wave.Length; i++)
        {
            Assert.Equal(TplA.New(i), wave[i].Ref<TplA>());
            Assert.Equal(TplB.New(i + 1), wave[i].Ref<TplB>());
        }

        // empty destination spawns nothing, null factory throws
        template.Spawn(Span<Entity>.Empty, i => (TplA.New(i), TplB.New(i + 1)));
        Assert.Equal(6, world.Count);
        Assert.Throws<ArgumentNullException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, (Func<int, (TplA, TplB)>)null!);
        });
    }


    [Fact]
    public void Span_Parallel_Spawn_Blits_Per_Entity_Values()
    {
        using var world = new World();
        using var template = Template(world);

        const int count = 5;
        var values0 = new TplA[count];
        var values1 = new TplB[count];
        for (var i = 0; i < count; i++)
        {
            values0[i] = TplA.New(i * 10 + 0);
            values1[i] = TplB.New(i * 10 + 1);
        }

        var wave = new Entity[count];
        Assert.Same(template, template.Spawn(wave, values0, values1));

        for (var i = 0; i < count; i++)
        {
            Assert.Equal(values0[i], wave[i].Ref<TplA>());
            Assert.Equal(values1[i], wave[i].Ref<TplB>());
        }

        // empty destination with empty values spawns nothing
        template.Spawn(Span<Entity>.Empty, Array.Empty<TplA>(), Array.Empty<TplB>());
        Assert.Equal(count, world.Count);
    }


    [Fact]
    public void Span_Parallel_Spawn_Rejects_Mismatched_Lengths()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[2], new TplB[3]);
        });

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[3], new TplB[2]);
        });

        Assert.Equal(0, world.Count);
    }


    [Fact]
    public void Add_Variants_Bake_Into_Template()
    {
        using var world = new World();
        var target = world.Spawn();
        var other = world.Spawn();
        var linked = BakedLink.New(7);

        using var template = Template(world)
            .Add(BakedVal.New(1))          // Add<T>(T)
            .Add(BakedVal.New(2))          // replaces the existing value
            .Add<BakedTag>()               // Add<C>() default
            .Add<BakedRel>(target)         // Add<T>(Entity) newable relation
            .Add(BakedRel.New(3), other)   // Add<R>(R, Entity) valued relation
            .Add(Link.With(linked));       // Add<T>(Link<T>) object link

        var entity = template.Spawn(TplA.New(0), TplB.New(0));

        Assert.Equal(BakedVal.New(2), entity.Ref<BakedVal>());
        Assert.True(entity.Has<BakedTag>());
        Assert.True(entity.Has<BakedRel>(target));
        Assert.True(entity.Has<BakedRel>(other));
        Assert.True(entity.Has(Link.With(linked)));
    }


    [Fact]
    public void Remove_Variants_Unbake_From_Template()
    {
        using var world = new World();
        var target = world.Spawn();
        var linked = BakedLink.New(7);
        var linked2 = BakedLink.New(8);

        using var template = Template(world)
            .Add(BakedVal.New(1))
            .Add<BakedTag>()
            .Add(BakedRel.New(3), target)
            .Add(Link.With(linked))
            .Add(Link.With(linked2))
            .Remove<BakedVal>()            // Remove<T>()
            .Remove<BakedRel>(target)      // Remove<T>(Entity)
            .Remove(linked)                // Remove<L>(L)
            .Remove(Link.With(linked2));   // Remove<L>(Link<L>)

        var entity = template.Spawn(TplA.New(0), TplB.New(0));

        Assert.False(entity.Has<BakedVal>());
        Assert.True(entity.Has<BakedTag>()); // untouched survivor
        Assert.False(entity.Has<BakedRel>(target));
        Assert.False(entity.Has(Link.With(linked)));
        Assert.False(entity.Has(Link.With(linked2)));
    }


    [Fact]
    public void Required_Components_Cannot_Be_Added_Or_Removed()
    {
        using var world = new World();
        using var template = Template(world);
        Assert.Throws<InvalidOperationException>(() => template.Add(TplA.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplA>());
        Assert.Throws<InvalidOperationException>(() => template.Add(TplB.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplB>());
    }


    [Fact]
    public void Needs_Widens_With_Relation_Requirement()
    {
        using var world = new World();
        var target = world.Spawn();

        using var template = Template(world).Needs<BakedRel>(target); // target baked, value per-spawn
        var entity = template.Spawn(TplA.New(0), TplB.New(0), BakedRel.New(9));

        Assert.True(entity.Has<BakedRel>(target));
        Assert.Equal(BakedRel.New(9), entity.Ref<BakedRel>(Match.Relation(target)));
    }


    [Fact]
    public void Needs_Conflicts_Throw()
    {
        using var world = new World();

        // duplicate requirement
        using var template = Template(world);
        Assert.Throws<InvalidOperationException>(() => template.Needs<TplA>());

        // requirement of an already-baked component
        using var baked = Template(world).Add(BakedVal.New(1));
        Assert.Throws<InvalidOperationException>(() => baked.Needs<BakedVal>());
    }


    [Fact]
    public void Consumed_Template_Is_Inert()
    {
        using var world = new World();

        var narrow = Template(world);
        using var wide = narrow.Needs<BakedVal>();

        narrow.Dispose(); // no-op, ownership moved on
        narrow.Dispose();
        Assert.Throws<ObjectDisposedException>(() => narrow.Add<BakedTag>());
        Assert.Throws<ObjectDisposedException>(() => narrow.Spawn(TplA.New(0), TplB.New(0)));

        // the wide template inherited the state and works
        var entity = wide.Spawn(TplA.New(1), TplB.New(2), BakedVal.New(42));
        Assert.Equal(BakedVal.New(42), entity.Ref<BakedVal>());
        Assert.Equal(TplA.New(1), entity.Ref<TplA>());
        Assert.Equal(TplB.New(2), entity.Ref<TplB>());
    }


    [Fact]
    public void Dispose_Semantics()
    {
        using var world = new World();

        var template = Template(world);
        template.Dispose();

        Assert.Throws<ObjectDisposedException>(() => template.Dispose());
        Assert.Throws<ObjectDisposedException>(() => template.Add(BakedVal.New(1)));
        Assert.Throws<ObjectDisposedException>(() => template.Spawn(TplA.New(0), TplB.New(0)));
    }
}

/// <summary>
/// Generated EntityTemplate battery: arity 3 (TplA, TplB, TplC).
/// </summary>
public class EntityTemplate3Tests
{
    private static EntityTemplate<TplA, TplB, TplC> Template(World world) => world.Template().Needs<TplA>().Needs<TplB>().Needs<TplC>();


    [Fact]
    public void Single_Spawn_Provides_Required_Values()
    {
        using var world = new World();
        using var template = Template(world);

        var entity = template.Spawn(TplA.New(0), TplB.New(10), TplC.New(20));

        Assert.True(entity.Alive);
        Assert.Equal(TplA.New(0), entity.Ref<TplA>());
        Assert.Equal(TplB.New(10), entity.Ref<TplB>());
        Assert.Equal(TplC.New(20), entity.Ref<TplC>());
    }


    [Fact]
    public void Uniform_Bulk_Spawn_Shares_Values()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Same(template, template.Spawn(5, TplA.New(1), TplB.New(2), TplC.New(3)));
        Assert.Equal(5, world.Count);
        foreach (var entity in world)
        {
            Assert.Equal(TplA.New(1), entity.Ref<TplA>());
            Assert.Equal(TplB.New(2), entity.Ref<TplB>());
            Assert.Equal(TplC.New(3), entity.Ref<TplC>());
        }

        // zero and negative counts spawn nothing
        template.Spawn(0, TplA.New(9), TplB.New(9), TplC.New(9));
        template.Spawn(-3, TplA.New(9), TplB.New(9), TplC.New(9));
        Assert.Equal(5, world.Count);
    }


    [Fact]
    public void Uniform_Span_Spawn_Delivers_Handles()
    {
        using var world = new World();
        using var template = Template(world);

        var wave = new Entity[4];
        Assert.Same(template, template.Spawn(wave, TplA.New(2), TplB.New(3), TplC.New(4)));

        foreach (var entity in wave)
        {
            Assert.True(entity.Alive);
            Assert.Equal(TplA.New(2), entity.Ref<TplA>());
            Assert.Equal(TplB.New(3), entity.Ref<TplB>());
            Assert.Equal(TplC.New(4), entity.Ref<TplC>());
        }

        // empty destination spawns nothing
        template.Spawn(Span<Entity>.Empty, TplA.New(9), TplB.New(9), TplC.New(9));
        Assert.Equal(4, world.Count);
    }


    [Fact]
    public void Factory_Spawn_Provides_Per_Entity_Values()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Same(template, template.Spawn(7, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2))));
        Assert.Equal(7, world.Count);

        var seen = new HashSet<int>();
        foreach (var entity in world)
        {
            var index = entity.Ref<TplA>().Value;
            Assert.True(seen.Add(index));
            Assert.Equal(TplB.New(index + 1), entity.Ref<TplB>());
            Assert.Equal(TplC.New(index + 2), entity.Ref<TplC>());
        }
        Assert.Equal(Enumerable.Range(0, 7).ToHashSet(), seen);

        // zero count spawns nothing, null factory throws
        template.Spawn(0, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2)));
        Assert.Equal(7, world.Count);
        Assert.Throws<ArgumentNullException>(() => template.Spawn(5, (Func<int, (TplA, TplB, TplC)>)null!));
    }


    [Fact]
    public void Factory_Span_Spawn_Delivers_Handles()
    {
        using var world = new World();
        using var template = Template(world);

        var wave = new Entity[6];
        Assert.Same(template, template.Spawn(wave, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2))));

        for (var i = 0; i < wave.Length; i++)
        {
            Assert.Equal(TplA.New(i), wave[i].Ref<TplA>());
            Assert.Equal(TplB.New(i + 1), wave[i].Ref<TplB>());
            Assert.Equal(TplC.New(i + 2), wave[i].Ref<TplC>());
        }

        // empty destination spawns nothing, null factory throws
        template.Spawn(Span<Entity>.Empty, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2)));
        Assert.Equal(6, world.Count);
        Assert.Throws<ArgumentNullException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, (Func<int, (TplA, TplB, TplC)>)null!);
        });
    }


    [Fact]
    public void Span_Parallel_Spawn_Blits_Per_Entity_Values()
    {
        using var world = new World();
        using var template = Template(world);

        const int count = 5;
        var values0 = new TplA[count];
        var values1 = new TplB[count];
        var values2 = new TplC[count];
        for (var i = 0; i < count; i++)
        {
            values0[i] = TplA.New(i * 10 + 0);
            values1[i] = TplB.New(i * 10 + 1);
            values2[i] = TplC.New(i * 10 + 2);
        }

        var wave = new Entity[count];
        Assert.Same(template, template.Spawn(wave, values0, values1, values2));

        for (var i = 0; i < count; i++)
        {
            Assert.Equal(values0[i], wave[i].Ref<TplA>());
            Assert.Equal(values1[i], wave[i].Ref<TplB>());
            Assert.Equal(values2[i], wave[i].Ref<TplC>());
        }

        // empty destination with empty values spawns nothing
        template.Spawn(Span<Entity>.Empty, Array.Empty<TplA>(), Array.Empty<TplB>(), Array.Empty<TplC>());
        Assert.Equal(count, world.Count);
    }


    [Fact]
    public void Span_Parallel_Spawn_Rejects_Mismatched_Lengths()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[2], new TplB[3], new TplC[3]);
        });

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[3], new TplB[2], new TplC[3]);
        });

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[3], new TplB[3], new TplC[2]);
        });

        Assert.Equal(0, world.Count);
    }


    [Fact]
    public void Add_Variants_Bake_Into_Template()
    {
        using var world = new World();
        var target = world.Spawn();
        var other = world.Spawn();
        var linked = BakedLink.New(7);

        using var template = Template(world)
            .Add(BakedVal.New(1))          // Add<T>(T)
            .Add(BakedVal.New(2))          // replaces the existing value
            .Add<BakedTag>()               // Add<C>() default
            .Add<BakedRel>(target)         // Add<T>(Entity) newable relation
            .Add(BakedRel.New(3), other)   // Add<R>(R, Entity) valued relation
            .Add(Link.With(linked));       // Add<T>(Link<T>) object link

        var entity = template.Spawn(TplA.New(0), TplB.New(0), TplC.New(0));

        Assert.Equal(BakedVal.New(2), entity.Ref<BakedVal>());
        Assert.True(entity.Has<BakedTag>());
        Assert.True(entity.Has<BakedRel>(target));
        Assert.True(entity.Has<BakedRel>(other));
        Assert.True(entity.Has(Link.With(linked)));
    }


    [Fact]
    public void Remove_Variants_Unbake_From_Template()
    {
        using var world = new World();
        var target = world.Spawn();
        var linked = BakedLink.New(7);
        var linked2 = BakedLink.New(8);

        using var template = Template(world)
            .Add(BakedVal.New(1))
            .Add<BakedTag>()
            .Add(BakedRel.New(3), target)
            .Add(Link.With(linked))
            .Add(Link.With(linked2))
            .Remove<BakedVal>()            // Remove<T>()
            .Remove<BakedRel>(target)      // Remove<T>(Entity)
            .Remove(linked)                // Remove<L>(L)
            .Remove(Link.With(linked2));   // Remove<L>(Link<L>)

        var entity = template.Spawn(TplA.New(0), TplB.New(0), TplC.New(0));

        Assert.False(entity.Has<BakedVal>());
        Assert.True(entity.Has<BakedTag>()); // untouched survivor
        Assert.False(entity.Has<BakedRel>(target));
        Assert.False(entity.Has(Link.With(linked)));
        Assert.False(entity.Has(Link.With(linked2)));
    }


    [Fact]
    public void Required_Components_Cannot_Be_Added_Or_Removed()
    {
        using var world = new World();
        using var template = Template(world);
        Assert.Throws<InvalidOperationException>(() => template.Add(TplA.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplA>());
        Assert.Throws<InvalidOperationException>(() => template.Add(TplB.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplB>());
        Assert.Throws<InvalidOperationException>(() => template.Add(TplC.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplC>());
    }


    [Fact]
    public void Needs_Widens_With_Relation_Requirement()
    {
        using var world = new World();
        var target = world.Spawn();

        using var template = Template(world).Needs<BakedRel>(target); // target baked, value per-spawn
        var entity = template.Spawn(TplA.New(0), TplB.New(0), TplC.New(0), BakedRel.New(9));

        Assert.True(entity.Has<BakedRel>(target));
        Assert.Equal(BakedRel.New(9), entity.Ref<BakedRel>(Match.Relation(target)));
    }


    [Fact]
    public void Needs_Conflicts_Throw()
    {
        using var world = new World();

        // duplicate requirement
        using var template = Template(world);
        Assert.Throws<InvalidOperationException>(() => template.Needs<TplA>());

        // requirement of an already-baked component
        using var baked = Template(world).Add(BakedVal.New(1));
        Assert.Throws<InvalidOperationException>(() => baked.Needs<BakedVal>());
    }


    [Fact]
    public void Consumed_Template_Is_Inert()
    {
        using var world = new World();

        var narrow = Template(world);
        using var wide = narrow.Needs<BakedVal>();

        narrow.Dispose(); // no-op, ownership moved on
        narrow.Dispose();
        Assert.Throws<ObjectDisposedException>(() => narrow.Add<BakedTag>());
        Assert.Throws<ObjectDisposedException>(() => narrow.Spawn(TplA.New(0), TplB.New(0), TplC.New(0)));

        // the wide template inherited the state and works
        var entity = wide.Spawn(TplA.New(1), TplB.New(2), TplC.New(3), BakedVal.New(42));
        Assert.Equal(BakedVal.New(42), entity.Ref<BakedVal>());
        Assert.Equal(TplA.New(1), entity.Ref<TplA>());
        Assert.Equal(TplB.New(2), entity.Ref<TplB>());
        Assert.Equal(TplC.New(3), entity.Ref<TplC>());
    }


    [Fact]
    public void Dispose_Semantics()
    {
        using var world = new World();

        var template = Template(world);
        template.Dispose();

        Assert.Throws<ObjectDisposedException>(() => template.Dispose());
        Assert.Throws<ObjectDisposedException>(() => template.Add(BakedVal.New(1)));
        Assert.Throws<ObjectDisposedException>(() => template.Spawn(TplA.New(0), TplB.New(0), TplC.New(0)));
    }
}

/// <summary>
/// Generated EntityTemplate battery: arity 4 (TplA, TplB, TplC, TplD).
/// </summary>
public class EntityTemplate4Tests
{
    private static EntityTemplate<TplA, TplB, TplC, TplD> Template(World world) => world.Template().Needs<TplA>().Needs<TplB>().Needs<TplC>().Needs<TplD>();


    [Fact]
    public void Single_Spawn_Provides_Required_Values()
    {
        using var world = new World();
        using var template = Template(world);

        var entity = template.Spawn(TplA.New(0), TplB.New(10), TplC.New(20), TplD.New(30));

        Assert.True(entity.Alive);
        Assert.Equal(TplA.New(0), entity.Ref<TplA>());
        Assert.Equal(TplB.New(10), entity.Ref<TplB>());
        Assert.Equal(TplC.New(20), entity.Ref<TplC>());
        Assert.Equal(TplD.New(30), entity.Ref<TplD>());
    }


    [Fact]
    public void Uniform_Bulk_Spawn_Shares_Values()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Same(template, template.Spawn(5, TplA.New(1), TplB.New(2), TplC.New(3), TplD.New(4)));
        Assert.Equal(5, world.Count);
        foreach (var entity in world)
        {
            Assert.Equal(TplA.New(1), entity.Ref<TplA>());
            Assert.Equal(TplB.New(2), entity.Ref<TplB>());
            Assert.Equal(TplC.New(3), entity.Ref<TplC>());
            Assert.Equal(TplD.New(4), entity.Ref<TplD>());
        }

        // zero and negative counts spawn nothing
        template.Spawn(0, TplA.New(9), TplB.New(9), TplC.New(9), TplD.New(9));
        template.Spawn(-3, TplA.New(9), TplB.New(9), TplC.New(9), TplD.New(9));
        Assert.Equal(5, world.Count);
    }


    [Fact]
    public void Uniform_Span_Spawn_Delivers_Handles()
    {
        using var world = new World();
        using var template = Template(world);

        var wave = new Entity[4];
        Assert.Same(template, template.Spawn(wave, TplA.New(2), TplB.New(3), TplC.New(4), TplD.New(5)));

        foreach (var entity in wave)
        {
            Assert.True(entity.Alive);
            Assert.Equal(TplA.New(2), entity.Ref<TplA>());
            Assert.Equal(TplB.New(3), entity.Ref<TplB>());
            Assert.Equal(TplC.New(4), entity.Ref<TplC>());
            Assert.Equal(TplD.New(5), entity.Ref<TplD>());
        }

        // empty destination spawns nothing
        template.Spawn(Span<Entity>.Empty, TplA.New(9), TplB.New(9), TplC.New(9), TplD.New(9));
        Assert.Equal(4, world.Count);
    }


    [Fact]
    public void Factory_Spawn_Provides_Per_Entity_Values()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Same(template, template.Spawn(7, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2), TplD.New(i + 3))));
        Assert.Equal(7, world.Count);

        var seen = new HashSet<int>();
        foreach (var entity in world)
        {
            var index = entity.Ref<TplA>().Value;
            Assert.True(seen.Add(index));
            Assert.Equal(TplB.New(index + 1), entity.Ref<TplB>());
            Assert.Equal(TplC.New(index + 2), entity.Ref<TplC>());
            Assert.Equal(TplD.New(index + 3), entity.Ref<TplD>());
        }
        Assert.Equal(Enumerable.Range(0, 7).ToHashSet(), seen);

        // zero count spawns nothing, null factory throws
        template.Spawn(0, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2), TplD.New(i + 3)));
        Assert.Equal(7, world.Count);
        Assert.Throws<ArgumentNullException>(() => template.Spawn(5, (Func<int, (TplA, TplB, TplC, TplD)>)null!));
    }


    [Fact]
    public void Factory_Span_Spawn_Delivers_Handles()
    {
        using var world = new World();
        using var template = Template(world);

        var wave = new Entity[6];
        Assert.Same(template, template.Spawn(wave, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2), TplD.New(i + 3))));

        for (var i = 0; i < wave.Length; i++)
        {
            Assert.Equal(TplA.New(i), wave[i].Ref<TplA>());
            Assert.Equal(TplB.New(i + 1), wave[i].Ref<TplB>());
            Assert.Equal(TplC.New(i + 2), wave[i].Ref<TplC>());
            Assert.Equal(TplD.New(i + 3), wave[i].Ref<TplD>());
        }

        // empty destination spawns nothing, null factory throws
        template.Spawn(Span<Entity>.Empty, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2), TplD.New(i + 3)));
        Assert.Equal(6, world.Count);
        Assert.Throws<ArgumentNullException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, (Func<int, (TplA, TplB, TplC, TplD)>)null!);
        });
    }


    [Fact]
    public void Span_Parallel_Spawn_Blits_Per_Entity_Values()
    {
        using var world = new World();
        using var template = Template(world);

        const int count = 5;
        var values0 = new TplA[count];
        var values1 = new TplB[count];
        var values2 = new TplC[count];
        var values3 = new TplD[count];
        for (var i = 0; i < count; i++)
        {
            values0[i] = TplA.New(i * 10 + 0);
            values1[i] = TplB.New(i * 10 + 1);
            values2[i] = TplC.New(i * 10 + 2);
            values3[i] = TplD.New(i * 10 + 3);
        }

        var wave = new Entity[count];
        Assert.Same(template, template.Spawn(wave, values0, values1, values2, values3));

        for (var i = 0; i < count; i++)
        {
            Assert.Equal(values0[i], wave[i].Ref<TplA>());
            Assert.Equal(values1[i], wave[i].Ref<TplB>());
            Assert.Equal(values2[i], wave[i].Ref<TplC>());
            Assert.Equal(values3[i], wave[i].Ref<TplD>());
        }

        // empty destination with empty values spawns nothing
        template.Spawn(Span<Entity>.Empty, Array.Empty<TplA>(), Array.Empty<TplB>(), Array.Empty<TplC>(), Array.Empty<TplD>());
        Assert.Equal(count, world.Count);
    }


    [Fact]
    public void Span_Parallel_Spawn_Rejects_Mismatched_Lengths()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[2], new TplB[3], new TplC[3], new TplD[3]);
        });

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[3], new TplB[2], new TplC[3], new TplD[3]);
        });

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[3], new TplB[3], new TplC[2], new TplD[3]);
        });

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[3], new TplB[3], new TplC[3], new TplD[2]);
        });

        Assert.Equal(0, world.Count);
    }


    [Fact]
    public void Add_Variants_Bake_Into_Template()
    {
        using var world = new World();
        var target = world.Spawn();
        var other = world.Spawn();
        var linked = BakedLink.New(7);

        using var template = Template(world)
            .Add(BakedVal.New(1))          // Add<T>(T)
            .Add(BakedVal.New(2))          // replaces the existing value
            .Add<BakedTag>()               // Add<C>() default
            .Add<BakedRel>(target)         // Add<T>(Entity) newable relation
            .Add(BakedRel.New(3), other)   // Add<R>(R, Entity) valued relation
            .Add(Link.With(linked));       // Add<T>(Link<T>) object link

        var entity = template.Spawn(TplA.New(0), TplB.New(0), TplC.New(0), TplD.New(0));

        Assert.Equal(BakedVal.New(2), entity.Ref<BakedVal>());
        Assert.True(entity.Has<BakedTag>());
        Assert.True(entity.Has<BakedRel>(target));
        Assert.True(entity.Has<BakedRel>(other));
        Assert.True(entity.Has(Link.With(linked)));
    }


    [Fact]
    public void Remove_Variants_Unbake_From_Template()
    {
        using var world = new World();
        var target = world.Spawn();
        var linked = BakedLink.New(7);
        var linked2 = BakedLink.New(8);

        using var template = Template(world)
            .Add(BakedVal.New(1))
            .Add<BakedTag>()
            .Add(BakedRel.New(3), target)
            .Add(Link.With(linked))
            .Add(Link.With(linked2))
            .Remove<BakedVal>()            // Remove<T>()
            .Remove<BakedRel>(target)      // Remove<T>(Entity)
            .Remove(linked)                // Remove<L>(L)
            .Remove(Link.With(linked2));   // Remove<L>(Link<L>)

        var entity = template.Spawn(TplA.New(0), TplB.New(0), TplC.New(0), TplD.New(0));

        Assert.False(entity.Has<BakedVal>());
        Assert.True(entity.Has<BakedTag>()); // untouched survivor
        Assert.False(entity.Has<BakedRel>(target));
        Assert.False(entity.Has(Link.With(linked)));
        Assert.False(entity.Has(Link.With(linked2)));
    }


    [Fact]
    public void Required_Components_Cannot_Be_Added_Or_Removed()
    {
        using var world = new World();
        using var template = Template(world);
        Assert.Throws<InvalidOperationException>(() => template.Add(TplA.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplA>());
        Assert.Throws<InvalidOperationException>(() => template.Add(TplB.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplB>());
        Assert.Throws<InvalidOperationException>(() => template.Add(TplC.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplC>());
        Assert.Throws<InvalidOperationException>(() => template.Add(TplD.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplD>());
    }


    [Fact]
    public void Needs_Widens_With_Relation_Requirement()
    {
        using var world = new World();
        var target = world.Spawn();

        using var template = Template(world).Needs<BakedRel>(target); // target baked, value per-spawn
        var entity = template.Spawn(TplA.New(0), TplB.New(0), TplC.New(0), TplD.New(0), BakedRel.New(9));

        Assert.True(entity.Has<BakedRel>(target));
        Assert.Equal(BakedRel.New(9), entity.Ref<BakedRel>(Match.Relation(target)));
    }


    [Fact]
    public void Needs_Conflicts_Throw()
    {
        using var world = new World();

        // duplicate requirement
        using var template = Template(world);
        Assert.Throws<InvalidOperationException>(() => template.Needs<TplA>());

        // requirement of an already-baked component
        using var baked = Template(world).Add(BakedVal.New(1));
        Assert.Throws<InvalidOperationException>(() => baked.Needs<BakedVal>());
    }


    [Fact]
    public void Consumed_Template_Is_Inert()
    {
        using var world = new World();

        var narrow = Template(world);
        using var wide = narrow.Needs<BakedVal>();

        narrow.Dispose(); // no-op, ownership moved on
        narrow.Dispose();
        Assert.Throws<ObjectDisposedException>(() => narrow.Add<BakedTag>());
        Assert.Throws<ObjectDisposedException>(() => narrow.Spawn(TplA.New(0), TplB.New(0), TplC.New(0), TplD.New(0)));

        // the wide template inherited the state and works
        var entity = wide.Spawn(TplA.New(1), TplB.New(2), TplC.New(3), TplD.New(4), BakedVal.New(42));
        Assert.Equal(BakedVal.New(42), entity.Ref<BakedVal>());
        Assert.Equal(TplA.New(1), entity.Ref<TplA>());
        Assert.Equal(TplB.New(2), entity.Ref<TplB>());
        Assert.Equal(TplC.New(3), entity.Ref<TplC>());
        Assert.Equal(TplD.New(4), entity.Ref<TplD>());
    }


    [Fact]
    public void Dispose_Semantics()
    {
        using var world = new World();

        var template = Template(world);
        template.Dispose();

        Assert.Throws<ObjectDisposedException>(() => template.Dispose());
        Assert.Throws<ObjectDisposedException>(() => template.Add(BakedVal.New(1)));
        Assert.Throws<ObjectDisposedException>(() => template.Spawn(TplA.New(0), TplB.New(0), TplC.New(0), TplD.New(0)));
    }
}

/// <summary>
/// Generated EntityTemplate battery: arity 5 (TplA, TplB, TplC, TplD, TplE).
/// </summary>
public class EntityTemplate5Tests
{
    private static EntityTemplate<TplA, TplB, TplC, TplD, TplE> Template(World world) => world.Template().Needs<TplA>().Needs<TplB>().Needs<TplC>().Needs<TplD>().Needs<TplE>();


    [Fact]
    public void Single_Spawn_Provides_Required_Values()
    {
        using var world = new World();
        using var template = Template(world);

        var entity = template.Spawn(TplA.New(0), TplB.New(10), TplC.New(20), TplD.New(30), TplE.New(40));

        Assert.True(entity.Alive);
        Assert.Equal(TplA.New(0), entity.Ref<TplA>());
        Assert.Equal(TplB.New(10), entity.Ref<TplB>());
        Assert.Equal(TplC.New(20), entity.Ref<TplC>());
        Assert.Equal(TplD.New(30), entity.Ref<TplD>());
        Assert.Equal(TplE.New(40), entity.Ref<TplE>());
    }


    [Fact]
    public void Uniform_Bulk_Spawn_Shares_Values()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Same(template, template.Spawn(5, TplA.New(1), TplB.New(2), TplC.New(3), TplD.New(4), TplE.New(5)));
        Assert.Equal(5, world.Count);
        foreach (var entity in world)
        {
            Assert.Equal(TplA.New(1), entity.Ref<TplA>());
            Assert.Equal(TplB.New(2), entity.Ref<TplB>());
            Assert.Equal(TplC.New(3), entity.Ref<TplC>());
            Assert.Equal(TplD.New(4), entity.Ref<TplD>());
            Assert.Equal(TplE.New(5), entity.Ref<TplE>());
        }

        // zero and negative counts spawn nothing
        template.Spawn(0, TplA.New(9), TplB.New(9), TplC.New(9), TplD.New(9), TplE.New(9));
        template.Spawn(-3, TplA.New(9), TplB.New(9), TplC.New(9), TplD.New(9), TplE.New(9));
        Assert.Equal(5, world.Count);
    }


    [Fact]
    public void Uniform_Span_Spawn_Delivers_Handles()
    {
        using var world = new World();
        using var template = Template(world);

        var wave = new Entity[4];
        Assert.Same(template, template.Spawn(wave, TplA.New(2), TplB.New(3), TplC.New(4), TplD.New(5), TplE.New(6)));

        foreach (var entity in wave)
        {
            Assert.True(entity.Alive);
            Assert.Equal(TplA.New(2), entity.Ref<TplA>());
            Assert.Equal(TplB.New(3), entity.Ref<TplB>());
            Assert.Equal(TplC.New(4), entity.Ref<TplC>());
            Assert.Equal(TplD.New(5), entity.Ref<TplD>());
            Assert.Equal(TplE.New(6), entity.Ref<TplE>());
        }

        // empty destination spawns nothing
        template.Spawn(Span<Entity>.Empty, TplA.New(9), TplB.New(9), TplC.New(9), TplD.New(9), TplE.New(9));
        Assert.Equal(4, world.Count);
    }


    [Fact]
    public void Factory_Spawn_Provides_Per_Entity_Values()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Same(template, template.Spawn(7, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2), TplD.New(i + 3), TplE.New(i + 4))));
        Assert.Equal(7, world.Count);

        var seen = new HashSet<int>();
        foreach (var entity in world)
        {
            var index = entity.Ref<TplA>().Value;
            Assert.True(seen.Add(index));
            Assert.Equal(TplB.New(index + 1), entity.Ref<TplB>());
            Assert.Equal(TplC.New(index + 2), entity.Ref<TplC>());
            Assert.Equal(TplD.New(index + 3), entity.Ref<TplD>());
            Assert.Equal(TplE.New(index + 4), entity.Ref<TplE>());
        }
        Assert.Equal(Enumerable.Range(0, 7).ToHashSet(), seen);

        // zero count spawns nothing, null factory throws
        template.Spawn(0, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2), TplD.New(i + 3), TplE.New(i + 4)));
        Assert.Equal(7, world.Count);
        Assert.Throws<ArgumentNullException>(() => template.Spawn(5, (Func<int, (TplA, TplB, TplC, TplD, TplE)>)null!));
    }


    [Fact]
    public void Factory_Span_Spawn_Delivers_Handles()
    {
        using var world = new World();
        using var template = Template(world);

        var wave = new Entity[6];
        Assert.Same(template, template.Spawn(wave, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2), TplD.New(i + 3), TplE.New(i + 4))));

        for (var i = 0; i < wave.Length; i++)
        {
            Assert.Equal(TplA.New(i), wave[i].Ref<TplA>());
            Assert.Equal(TplB.New(i + 1), wave[i].Ref<TplB>());
            Assert.Equal(TplC.New(i + 2), wave[i].Ref<TplC>());
            Assert.Equal(TplD.New(i + 3), wave[i].Ref<TplD>());
            Assert.Equal(TplE.New(i + 4), wave[i].Ref<TplE>());
        }

        // empty destination spawns nothing, null factory throws
        template.Spawn(Span<Entity>.Empty, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2), TplD.New(i + 3), TplE.New(i + 4)));
        Assert.Equal(6, world.Count);
        Assert.Throws<ArgumentNullException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, (Func<int, (TplA, TplB, TplC, TplD, TplE)>)null!);
        });
    }


    [Fact]
    public void Span_Parallel_Spawn_Blits_Per_Entity_Values()
    {
        using var world = new World();
        using var template = Template(world);

        const int count = 5;
        var values0 = new TplA[count];
        var values1 = new TplB[count];
        var values2 = new TplC[count];
        var values3 = new TplD[count];
        var values4 = new TplE[count];
        for (var i = 0; i < count; i++)
        {
            values0[i] = TplA.New(i * 10 + 0);
            values1[i] = TplB.New(i * 10 + 1);
            values2[i] = TplC.New(i * 10 + 2);
            values3[i] = TplD.New(i * 10 + 3);
            values4[i] = TplE.New(i * 10 + 4);
        }

        var wave = new Entity[count];
        Assert.Same(template, template.Spawn(wave, values0, values1, values2, values3, values4));

        for (var i = 0; i < count; i++)
        {
            Assert.Equal(values0[i], wave[i].Ref<TplA>());
            Assert.Equal(values1[i], wave[i].Ref<TplB>());
            Assert.Equal(values2[i], wave[i].Ref<TplC>());
            Assert.Equal(values3[i], wave[i].Ref<TplD>());
            Assert.Equal(values4[i], wave[i].Ref<TplE>());
        }

        // empty destination with empty values spawns nothing
        template.Spawn(Span<Entity>.Empty, Array.Empty<TplA>(), Array.Empty<TplB>(), Array.Empty<TplC>(), Array.Empty<TplD>(), Array.Empty<TplE>());
        Assert.Equal(count, world.Count);
    }


    [Fact]
    public void Span_Parallel_Spawn_Rejects_Mismatched_Lengths()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[2], new TplB[3], new TplC[3], new TplD[3], new TplE[3]);
        });

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[3], new TplB[2], new TplC[3], new TplD[3], new TplE[3]);
        });

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[3], new TplB[3], new TplC[2], new TplD[3], new TplE[3]);
        });

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[3], new TplB[3], new TplC[3], new TplD[2], new TplE[3]);
        });

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[3], new TplB[3], new TplC[3], new TplD[3], new TplE[2]);
        });

        Assert.Equal(0, world.Count);
    }


    [Fact]
    public void Add_Variants_Bake_Into_Template()
    {
        using var world = new World();
        var target = world.Spawn();
        var other = world.Spawn();
        var linked = BakedLink.New(7);

        using var template = Template(world)
            .Add(BakedVal.New(1))          // Add<T>(T)
            .Add(BakedVal.New(2))          // replaces the existing value
            .Add<BakedTag>()               // Add<C>() default
            .Add<BakedRel>(target)         // Add<T>(Entity) newable relation
            .Add(BakedRel.New(3), other)   // Add<R>(R, Entity) valued relation
            .Add(Link.With(linked));       // Add<T>(Link<T>) object link

        var entity = template.Spawn(TplA.New(0), TplB.New(0), TplC.New(0), TplD.New(0), TplE.New(0));

        Assert.Equal(BakedVal.New(2), entity.Ref<BakedVal>());
        Assert.True(entity.Has<BakedTag>());
        Assert.True(entity.Has<BakedRel>(target));
        Assert.True(entity.Has<BakedRel>(other));
        Assert.True(entity.Has(Link.With(linked)));
    }


    [Fact]
    public void Remove_Variants_Unbake_From_Template()
    {
        using var world = new World();
        var target = world.Spawn();
        var linked = BakedLink.New(7);
        var linked2 = BakedLink.New(8);

        using var template = Template(world)
            .Add(BakedVal.New(1))
            .Add<BakedTag>()
            .Add(BakedRel.New(3), target)
            .Add(Link.With(linked))
            .Add(Link.With(linked2))
            .Remove<BakedVal>()            // Remove<T>()
            .Remove<BakedRel>(target)      // Remove<T>(Entity)
            .Remove(linked)                // Remove<L>(L)
            .Remove(Link.With(linked2));   // Remove<L>(Link<L>)

        var entity = template.Spawn(TplA.New(0), TplB.New(0), TplC.New(0), TplD.New(0), TplE.New(0));

        Assert.False(entity.Has<BakedVal>());
        Assert.True(entity.Has<BakedTag>()); // untouched survivor
        Assert.False(entity.Has<BakedRel>(target));
        Assert.False(entity.Has(Link.With(linked)));
        Assert.False(entity.Has(Link.With(linked2)));
    }


    [Fact]
    public void Required_Components_Cannot_Be_Added_Or_Removed()
    {
        using var world = new World();
        using var template = Template(world);
        Assert.Throws<InvalidOperationException>(() => template.Add(TplA.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplA>());
        Assert.Throws<InvalidOperationException>(() => template.Add(TplB.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplB>());
        Assert.Throws<InvalidOperationException>(() => template.Add(TplC.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplC>());
        Assert.Throws<InvalidOperationException>(() => template.Add(TplD.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplD>());
        Assert.Throws<InvalidOperationException>(() => template.Add(TplE.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplE>());
    }


    [Fact]
    public void Needs_Widens_With_Relation_Requirement()
    {
        using var world = new World();
        var target = world.Spawn();

        using var template = Template(world).Needs<BakedRel>(target); // target baked, value per-spawn
        var entity = template.Spawn(TplA.New(0), TplB.New(0), TplC.New(0), TplD.New(0), TplE.New(0), BakedRel.New(9));

        Assert.True(entity.Has<BakedRel>(target));
        Assert.Equal(BakedRel.New(9), entity.Ref<BakedRel>(Match.Relation(target)));
    }


    [Fact]
    public void Needs_Conflicts_Throw()
    {
        using var world = new World();

        // duplicate requirement
        using var template = Template(world);
        Assert.Throws<InvalidOperationException>(() => template.Needs<TplA>());

        // requirement of an already-baked component
        using var baked = Template(world).Add(BakedVal.New(1));
        Assert.Throws<InvalidOperationException>(() => baked.Needs<BakedVal>());
    }


    [Fact]
    public void Consumed_Template_Is_Inert()
    {
        using var world = new World();

        var narrow = Template(world);
        using var wide = narrow.Needs<BakedVal>();

        narrow.Dispose(); // no-op, ownership moved on
        narrow.Dispose();
        Assert.Throws<ObjectDisposedException>(() => narrow.Add<BakedTag>());
        Assert.Throws<ObjectDisposedException>(() => narrow.Spawn(TplA.New(0), TplB.New(0), TplC.New(0), TplD.New(0), TplE.New(0)));

        // the wide template inherited the state and works
        var entity = wide.Spawn(TplA.New(1), TplB.New(2), TplC.New(3), TplD.New(4), TplE.New(5), BakedVal.New(42));
        Assert.Equal(BakedVal.New(42), entity.Ref<BakedVal>());
        Assert.Equal(TplA.New(1), entity.Ref<TplA>());
        Assert.Equal(TplB.New(2), entity.Ref<TplB>());
        Assert.Equal(TplC.New(3), entity.Ref<TplC>());
        Assert.Equal(TplD.New(4), entity.Ref<TplD>());
        Assert.Equal(TplE.New(5), entity.Ref<TplE>());
    }


    [Fact]
    public void Dispose_Semantics()
    {
        using var world = new World();

        var template = Template(world);
        template.Dispose();

        Assert.Throws<ObjectDisposedException>(() => template.Dispose());
        Assert.Throws<ObjectDisposedException>(() => template.Add(BakedVal.New(1)));
        Assert.Throws<ObjectDisposedException>(() => template.Spawn(TplA.New(0), TplB.New(0), TplC.New(0), TplD.New(0), TplE.New(0)));
    }
}

/// <summary>
/// Generated EntityTemplate battery: arity 6 (TplA, TplB, TplC, TplD, TplE, TplF).
/// </summary>
public class EntityTemplate6Tests
{
    private static EntityTemplate<TplA, TplB, TplC, TplD, TplE, TplF> Template(World world) => world.Template().Needs<TplA>().Needs<TplB>().Needs<TplC>().Needs<TplD>().Needs<TplE>().Needs<TplF>();


    [Fact]
    public void Single_Spawn_Provides_Required_Values()
    {
        using var world = new World();
        using var template = Template(world);

        var entity = template.Spawn(TplA.New(0), TplB.New(10), TplC.New(20), TplD.New(30), TplE.New(40), TplF.New(50));

        Assert.True(entity.Alive);
        Assert.Equal(TplA.New(0), entity.Ref<TplA>());
        Assert.Equal(TplB.New(10), entity.Ref<TplB>());
        Assert.Equal(TplC.New(20), entity.Ref<TplC>());
        Assert.Equal(TplD.New(30), entity.Ref<TplD>());
        Assert.Equal(TplE.New(40), entity.Ref<TplE>());
        Assert.Equal(TplF.New(50), entity.Ref<TplF>());
    }


    [Fact]
    public void Uniform_Bulk_Spawn_Shares_Values()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Same(template, template.Spawn(5, TplA.New(1), TplB.New(2), TplC.New(3), TplD.New(4), TplE.New(5), TplF.New(6)));
        Assert.Equal(5, world.Count);
        foreach (var entity in world)
        {
            Assert.Equal(TplA.New(1), entity.Ref<TplA>());
            Assert.Equal(TplB.New(2), entity.Ref<TplB>());
            Assert.Equal(TplC.New(3), entity.Ref<TplC>());
            Assert.Equal(TplD.New(4), entity.Ref<TplD>());
            Assert.Equal(TplE.New(5), entity.Ref<TplE>());
            Assert.Equal(TplF.New(6), entity.Ref<TplF>());
        }

        // zero and negative counts spawn nothing
        template.Spawn(0, TplA.New(9), TplB.New(9), TplC.New(9), TplD.New(9), TplE.New(9), TplF.New(9));
        template.Spawn(-3, TplA.New(9), TplB.New(9), TplC.New(9), TplD.New(9), TplE.New(9), TplF.New(9));
        Assert.Equal(5, world.Count);
    }


    [Fact]
    public void Uniform_Span_Spawn_Delivers_Handles()
    {
        using var world = new World();
        using var template = Template(world);

        var wave = new Entity[4];
        Assert.Same(template, template.Spawn(wave, TplA.New(2), TplB.New(3), TplC.New(4), TplD.New(5), TplE.New(6), TplF.New(7)));

        foreach (var entity in wave)
        {
            Assert.True(entity.Alive);
            Assert.Equal(TplA.New(2), entity.Ref<TplA>());
            Assert.Equal(TplB.New(3), entity.Ref<TplB>());
            Assert.Equal(TplC.New(4), entity.Ref<TplC>());
            Assert.Equal(TplD.New(5), entity.Ref<TplD>());
            Assert.Equal(TplE.New(6), entity.Ref<TplE>());
            Assert.Equal(TplF.New(7), entity.Ref<TplF>());
        }

        // empty destination spawns nothing
        template.Spawn(Span<Entity>.Empty, TplA.New(9), TplB.New(9), TplC.New(9), TplD.New(9), TplE.New(9), TplF.New(9));
        Assert.Equal(4, world.Count);
    }


    [Fact]
    public void Factory_Spawn_Provides_Per_Entity_Values()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Same(template, template.Spawn(7, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2), TplD.New(i + 3), TplE.New(i + 4), TplF.New(i + 5))));
        Assert.Equal(7, world.Count);

        var seen = new HashSet<int>();
        foreach (var entity in world)
        {
            var index = entity.Ref<TplA>().Value;
            Assert.True(seen.Add(index));
            Assert.Equal(TplB.New(index + 1), entity.Ref<TplB>());
            Assert.Equal(TplC.New(index + 2), entity.Ref<TplC>());
            Assert.Equal(TplD.New(index + 3), entity.Ref<TplD>());
            Assert.Equal(TplE.New(index + 4), entity.Ref<TplE>());
            Assert.Equal(TplF.New(index + 5), entity.Ref<TplF>());
        }
        Assert.Equal(Enumerable.Range(0, 7).ToHashSet(), seen);

        // zero count spawns nothing, null factory throws
        template.Spawn(0, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2), TplD.New(i + 3), TplE.New(i + 4), TplF.New(i + 5)));
        Assert.Equal(7, world.Count);
        Assert.Throws<ArgumentNullException>(() => template.Spawn(5, (Func<int, (TplA, TplB, TplC, TplD, TplE, TplF)>)null!));
    }


    [Fact]
    public void Factory_Span_Spawn_Delivers_Handles()
    {
        using var world = new World();
        using var template = Template(world);

        var wave = new Entity[6];
        Assert.Same(template, template.Spawn(wave, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2), TplD.New(i + 3), TplE.New(i + 4), TplF.New(i + 5))));

        for (var i = 0; i < wave.Length; i++)
        {
            Assert.Equal(TplA.New(i), wave[i].Ref<TplA>());
            Assert.Equal(TplB.New(i + 1), wave[i].Ref<TplB>());
            Assert.Equal(TplC.New(i + 2), wave[i].Ref<TplC>());
            Assert.Equal(TplD.New(i + 3), wave[i].Ref<TplD>());
            Assert.Equal(TplE.New(i + 4), wave[i].Ref<TplE>());
            Assert.Equal(TplF.New(i + 5), wave[i].Ref<TplF>());
        }

        // empty destination spawns nothing, null factory throws
        template.Spawn(Span<Entity>.Empty, i => (TplA.New(i), TplB.New(i + 1), TplC.New(i + 2), TplD.New(i + 3), TplE.New(i + 4), TplF.New(i + 5)));
        Assert.Equal(6, world.Count);
        Assert.Throws<ArgumentNullException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, (Func<int, (TplA, TplB, TplC, TplD, TplE, TplF)>)null!);
        });
    }


    [Fact]
    public void Span_Parallel_Spawn_Blits_Per_Entity_Values()
    {
        using var world = new World();
        using var template = Template(world);

        const int count = 5;
        var values0 = new TplA[count];
        var values1 = new TplB[count];
        var values2 = new TplC[count];
        var values3 = new TplD[count];
        var values4 = new TplE[count];
        var values5 = new TplF[count];
        for (var i = 0; i < count; i++)
        {
            values0[i] = TplA.New(i * 10 + 0);
            values1[i] = TplB.New(i * 10 + 1);
            values2[i] = TplC.New(i * 10 + 2);
            values3[i] = TplD.New(i * 10 + 3);
            values4[i] = TplE.New(i * 10 + 4);
            values5[i] = TplF.New(i * 10 + 5);
        }

        var wave = new Entity[count];
        Assert.Same(template, template.Spawn(wave, values0, values1, values2, values3, values4, values5));

        for (var i = 0; i < count; i++)
        {
            Assert.Equal(values0[i], wave[i].Ref<TplA>());
            Assert.Equal(values1[i], wave[i].Ref<TplB>());
            Assert.Equal(values2[i], wave[i].Ref<TplC>());
            Assert.Equal(values3[i], wave[i].Ref<TplD>());
            Assert.Equal(values4[i], wave[i].Ref<TplE>());
            Assert.Equal(values5[i], wave[i].Ref<TplF>());
        }

        // empty destination with empty values spawns nothing
        template.Spawn(Span<Entity>.Empty, Array.Empty<TplA>(), Array.Empty<TplB>(), Array.Empty<TplC>(), Array.Empty<TplD>(), Array.Empty<TplE>(), Array.Empty<TplF>());
        Assert.Equal(count, world.Count);
    }


    [Fact]
    public void Span_Parallel_Spawn_Rejects_Mismatched_Lengths()
    {
        using var world = new World();
        using var template = Template(world);

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[2], new TplB[3], new TplC[3], new TplD[3], new TplE[3], new TplF[3]);
        });

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[3], new TplB[2], new TplC[3], new TplD[3], new TplE[3], new TplF[3]);
        });

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[3], new TplB[3], new TplC[2], new TplD[3], new TplE[3], new TplF[3]);
        });

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[3], new TplB[3], new TplC[3], new TplD[2], new TplE[3], new TplF[3]);
        });

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[3], new TplB[3], new TplC[3], new TplD[3], new TplE[2], new TplF[3]);
        });

        Assert.Throws<ArgumentException>(() =>
        {
            var destination = new Entity[3];
            template.Spawn(destination, new TplA[3], new TplB[3], new TplC[3], new TplD[3], new TplE[3], new TplF[2]);
        });

        Assert.Equal(0, world.Count);
    }


    [Fact]
    public void Add_Variants_Bake_Into_Template()
    {
        using var world = new World();
        var target = world.Spawn();
        var other = world.Spawn();
        var linked = BakedLink.New(7);

        using var template = Template(world)
            .Add(BakedVal.New(1))          // Add<T>(T)
            .Add(BakedVal.New(2))          // replaces the existing value
            .Add<BakedTag>()               // Add<C>() default
            .Add<BakedRel>(target)         // Add<T>(Entity) newable relation
            .Add(BakedRel.New(3), other)   // Add<R>(R, Entity) valued relation
            .Add(Link.With(linked));       // Add<T>(Link<T>) object link

        var entity = template.Spawn(TplA.New(0), TplB.New(0), TplC.New(0), TplD.New(0), TplE.New(0), TplF.New(0));

        Assert.Equal(BakedVal.New(2), entity.Ref<BakedVal>());
        Assert.True(entity.Has<BakedTag>());
        Assert.True(entity.Has<BakedRel>(target));
        Assert.True(entity.Has<BakedRel>(other));
        Assert.True(entity.Has(Link.With(linked)));
    }


    [Fact]
    public void Remove_Variants_Unbake_From_Template()
    {
        using var world = new World();
        var target = world.Spawn();
        var linked = BakedLink.New(7);
        var linked2 = BakedLink.New(8);

        using var template = Template(world)
            .Add(BakedVal.New(1))
            .Add<BakedTag>()
            .Add(BakedRel.New(3), target)
            .Add(Link.With(linked))
            .Add(Link.With(linked2))
            .Remove<BakedVal>()            // Remove<T>()
            .Remove<BakedRel>(target)      // Remove<T>(Entity)
            .Remove(linked)                // Remove<L>(L)
            .Remove(Link.With(linked2));   // Remove<L>(Link<L>)

        var entity = template.Spawn(TplA.New(0), TplB.New(0), TplC.New(0), TplD.New(0), TplE.New(0), TplF.New(0));

        Assert.False(entity.Has<BakedVal>());
        Assert.True(entity.Has<BakedTag>()); // untouched survivor
        Assert.False(entity.Has<BakedRel>(target));
        Assert.False(entity.Has(Link.With(linked)));
        Assert.False(entity.Has(Link.With(linked2)));
    }


    [Fact]
    public void Required_Components_Cannot_Be_Added_Or_Removed()
    {
        using var world = new World();
        using var template = Template(world);
        Assert.Throws<InvalidOperationException>(() => template.Add(TplA.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplA>());
        Assert.Throws<InvalidOperationException>(() => template.Add(TplB.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplB>());
        Assert.Throws<InvalidOperationException>(() => template.Add(TplC.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplC>());
        Assert.Throws<InvalidOperationException>(() => template.Add(TplD.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplD>());
        Assert.Throws<InvalidOperationException>(() => template.Add(TplE.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplE>());
        Assert.Throws<InvalidOperationException>(() => template.Add(TplF.New(1)));
        Assert.Throws<InvalidOperationException>(() => template.Remove<TplF>());
    }


    [Fact]
    public void Dispose_Semantics()
    {
        using var world = new World();

        var template = Template(world);
        template.Dispose();

        Assert.Throws<ObjectDisposedException>(() => template.Dispose());
        Assert.Throws<ObjectDisposedException>(() => template.Add(BakedVal.New(1)));
        Assert.Throws<ObjectDisposedException>(() => template.Spawn(TplA.New(0), TplB.New(0), TplC.New(0), TplD.New(0), TplE.New(0), TplF.New(0)));
    }
}
