//------------------------------------------------------------------------------
// <auto-generated>
//   This file is generated by EntityTemplate.tt
//   Do not modify directly.
//------------------------------------------------------------------------------
using System.Buffers;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using fennecs.CRUD;
using fennecs.pools;

// Date: 07/18/2026 08:19:26

namespace fennecs
{
    /// <summary>
    /// An Entity template with 1 required Component, declared via <c>Needs</c>.
    /// Values for the required Components must be provided at <c>Spawn</c>, enforced at compile time.
    /// </summary>
    /// <remarks>
    /// Call any <c>Spawn</c> overload to actually spawn Entities.
    /// </remarks>
    public sealed class EntityTemplate<C0> : IDisposable, IAddRemove<EntityTemplate<C0>>
        where C0 : notnull
    {
        #region Internals

        private readonly World _world;

        private PooledList<TypeExpression> _components;
        private PooledList<object> _values;

        // Type Expressions and Match terms of the required Components, index i belongs to Ci.
        private readonly TypeExpression[] _required;
        private readonly Match[] _matches;

        private bool _disposed;
        private bool _consumed;

        internal EntityTemplate(World world, PooledList<TypeExpression> components, PooledList<object> values, TypeExpression[] required, Match[] matches)
        {
            _world = world;
            _components = components;
            _values = values;
            _required = required;
            _matches = matches;
        }

        private void AssertMutable() => ObjectDisposedException.ThrowIf(_disposed || _consumed, this);

        private void AssertNotRequired(TypeExpression type)
        {
            if (Array.IndexOf(_required, type) >= 0)
                throw new InvalidOperationException($"Component {type} is a required Component of this template and must be provided at Spawn.");
        }

        private EntityTemplate<C0> AddComponent(TypeExpression type, object value)
        {
            AssertMutable();
            AssertNotRequired(type);
            if (_components.Contains(type))
            {
                // replace existing value
                _values[_components.IndexOf(type)] = value;
            }
            else
            {
                // add new value
                _components.Add(type);
                _values.Add(value);
            }
            return this;
        }

        private EntityTemplate<C0> RemoveComponent(TypeExpression type)
        {
            AssertMutable();
            AssertNotRequired(type);
            _values.RemoveAt(_components.IndexOf(type));
            _components.Remove(type);
            return this;
        }

        #endregion


        /// <inheritdoc cref="EntityTemplate.Add{T}(T)"/>
        public EntityTemplate<C0> Add<T>(T component) where T : notnull
        {
            var type = Comp<T>.Plain.Expression;
            return AddComponent(type, component);
        }

        /// <inheritdoc cref="EntityTemplate.Add{T}(Entity)"/>
        public EntityTemplate<C0> Add<T>(Entity target) where T : notnull, new() => Add(new T(), target);


        /// <inheritdoc cref="EntityTemplate.Add{C}()"/>
        public EntityTemplate<C0> Add<C>() where C : notnull, new() => Add(new C());


        /// <inheritdoc cref="EntityTemplate.Add{R}(R, Entity)"/>
        public EntityTemplate<C0> Add<R>(R value, Entity relation) where R : notnull
        {
            var type = TypeExpression.Of<R>(relation);
            return AddComponent(type, value);
        }


        /// <inheritdoc cref="EntityTemplate.Add{T}(Link{T})"/>
        public EntityTemplate<C0> Add<T>(Link<T> target) where T : class
        {
            var type = TypeExpression.Of<T>(target);
            return AddComponent(type, target.Object);
        }


        /// <inheritdoc cref="EntityTemplate.Remove{T}()"/>
        public EntityTemplate<C0> Remove<T>() where T : notnull
        {
            var type = Comp<T>.Plain.Expression;
            return RemoveComponent(type);
        }

        /// <inheritdoc cref="EntityTemplate.Remove{T}(Entity)"/>
        public EntityTemplate<C0> Remove<T>(Entity entity) where T : notnull
        {
            var type = TypeExpression.Of<T>(entity);
            return RemoveComponent(type);
        }

        /// <inheritdoc cref="EntityTemplate.Remove{L}(L)"/>
        public EntityTemplate<C0> Remove<L>(L linkedObject) where L : class => Remove(Link<L>.With(linkedObject));

        /// <inheritdoc cref="EntityTemplate.Remove{L}(Link{L})"/>
        public EntityTemplate<C0> Remove<L>(Link<L> link) where L : class
        {
            return RemoveComponent(link.TypeExpression);
        }

        /// <inheritdoc cref="EntityTemplate.Needs{C0}()"/>
        public EntityTemplate<C0, C1> Needs<C1>() where C1 : notnull => Needs<C1>(Comp<C1>.Plain.Expression, Match.Plain);

        /// <inheritdoc cref="EntityTemplate.Needs{C0}(Entity)"/>
        public EntityTemplate<C0, C1> Needs<C1>(Entity relation) where C1 : notnull => Needs<C1>(TypeExpression.Of<C1>(relation), Match.Relation(relation));

        private EntityTemplate<C0, C1> Needs<C1>(TypeExpression expression, Match match) where C1 : notnull
        {
            AssertMutable();
            if (Array.IndexOf(_required, expression) >= 0)
                throw new InvalidOperationException($"Component {expression} is already a required Component of this template.");
            if (_components.Contains(expression))
                throw new InvalidOperationException($"Component {expression} is already configured on this template. Remove it first, or provide it at Spawn instead.");

            _consumed = true;
            var (components, values) = (_components, _values);
            _components = null!;
            _values = null!;
            return new EntityTemplate<C0, C1>(_world, components, values, [.._required, expression], [.._matches, match]);
        }

        /// <summary>
        /// Spawns a single Entity with the configured Components and the provided required values.
        /// </summary>
        /// <param name="c0">value for the required Component C0</param>
        /// <returns>the spawned Entity</returns>
        public Entity Spawn(C0 c0)
        {
            Span<Entity> spawned = stackalloc Entity[1];
            Spawn(spawned, c0);
            return spawned[0];
        }

        /// <summary>
        /// Spawns <c>count</c> Entities with the configured Components; the whole wave shares
        /// the provided required values.
        /// </summary>
        /// <param name="count">number of Entities to spawn</param>
        /// <param name="c0">value for the required Component C0</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0> Spawn(int count, C0 c0)
        {
            AssertMutable();
            if (count <= 0) return this;

            using var components = PooledList<TypeExpression>.Rent();
            using var values = PooledList<object>.Rent();
            components.AddRange(_components);
            values.AddRange(_values);
            components.Add(_required[0]);
            values.Add(c0);
            _world.Spawn(count, components, values);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/> with the configured
        /// Components, writing their handles into the span; the whole wave shares the provided
        /// required values.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned</param>
        /// <param name="c0">value for the required Component C0</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0> Spawn(Span<Entity> destination, C0 c0)
        {
            AssertMutable();

            using var components = PooledList<TypeExpression>.Rent();
            using var values = PooledList<object>.Rent();
            components.AddRange(_components);
            values.AddRange(_values);
            components.Add(_required[0]);
            values.Add(c0);
            _world.Spawn(destination, components, values);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/>, taking each Entity's
        /// required values from the value spans at the same index, and writing the minted handles
        /// into <paramref name="destination"/>.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned, and all value spans must match it</param>
        /// <param name="values0">per-Entity values for the required Component C0; length must equal the destination's</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0> Spawn(Span<Entity> destination, ReadOnlySpan<C0> values0)
        {
            AssertMutable();
            if (values0.Length != destination.Length) throw new ArgumentException($"Length ({values0.Length}) must equal destination.Length ({destination.Length})", nameof(values0));
            if (destination.IsEmpty) return this;

            // Broadcast-spawn the wave (lands contiguously, in destination order, per aspect
            // archetype), then blit each value span straight into its storage slice. (no boxing)
            Spawn(destination, values0[0]);
            var slice0 = _world.ContiguousSlice<C0>(destination[0], _matches[0], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice0[^1], ref destination[^1].Ref<C0>(_matches[0])), "Spawn wave is not contiguous in Component storage.");
            values0.CopyTo(slice0);
            return this;
        }

        /// <summary>
        /// Spawns <c>count</c> Entities with the configured Components, calling <paramref name="factory"/>
        /// with each Entity's index to produce its required values.
        /// </summary>
        /// <param name="count">number of Entities to spawn</param>
        /// <param name="factory">produces the required values for the Entity at each index</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0> Spawn(int count, Func<int, C0> factory)
        {
            AssertMutable();
            ArgumentNullException.ThrowIfNull(factory);
            if (count <= 0) return this;

            var entities = ArrayPool<Entity>.Shared.Rent(count);
            Spawn(entities.AsSpan(0, count), factory);
            ArrayPool<Entity>.Shared.Return(entities);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/>, calling <paramref name="factory"/>
        /// with each Entity's index to produce its required values, and writing the minted handles
        /// into <paramref name="destination"/>.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned</param>
        /// <param name="factory">produces the required values for the Entity at each index</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0> Spawn(Span<Entity> destination, Func<int, C0> factory)
        {
            AssertMutable();
            ArgumentNullException.ThrowIfNull(factory);
            if (destination.IsEmpty) return this;

            var count = destination.Length;
            var rented0 = ArrayPool<C0>.Shared.Rent(count);
            for (var i = 0; i < count; i++)
            {
                rented0[i] = factory(i);
            }
            Spawn(destination, rented0.AsSpan(0, count));
            ArrayPool<C0>.Shared.Return(rented0, RuntimeHelpers.IsReferenceOrContainsReferences<C0>());
            return this;
        }

        /// <inheritdoc />
        public void Dispose()
        {
            if (_consumed) return; // ownership moved to a wider template via Needs

            ObjectDisposedException.ThrowIf(_disposed, this);
            _disposed = true;

            _components.Dispose();
            _components = null!;

            _values.Dispose();
            _values = null!;
        }
    }

    /// <summary>
    /// An Entity template with 2 required Components, declared via <c>Needs</c>.
    /// Values for the required Components must be provided at <c>Spawn</c>, enforced at compile time.
    /// </summary>
    /// <remarks>
    /// Call any <c>Spawn</c> overload to actually spawn Entities.
    /// </remarks>
    public sealed class EntityTemplate<C0, C1> : IDisposable, IAddRemove<EntityTemplate<C0, C1>>
        where C0 : notnull
        where C1 : notnull
    {
        #region Internals

        private readonly World _world;

        private PooledList<TypeExpression> _components;
        private PooledList<object> _values;

        // Type Expressions and Match terms of the required Components, index i belongs to Ci.
        private readonly TypeExpression[] _required;
        private readonly Match[] _matches;

        private bool _disposed;
        private bool _consumed;

        internal EntityTemplate(World world, PooledList<TypeExpression> components, PooledList<object> values, TypeExpression[] required, Match[] matches)
        {
            _world = world;
            _components = components;
            _values = values;
            _required = required;
            _matches = matches;
        }

        private void AssertMutable() => ObjectDisposedException.ThrowIf(_disposed || _consumed, this);

        private void AssertNotRequired(TypeExpression type)
        {
            if (Array.IndexOf(_required, type) >= 0)
                throw new InvalidOperationException($"Component {type} is a required Component of this template and must be provided at Spawn.");
        }

        private EntityTemplate<C0, C1> AddComponent(TypeExpression type, object value)
        {
            AssertMutable();
            AssertNotRequired(type);
            if (_components.Contains(type))
            {
                // replace existing value
                _values[_components.IndexOf(type)] = value;
            }
            else
            {
                // add new value
                _components.Add(type);
                _values.Add(value);
            }
            return this;
        }

        private EntityTemplate<C0, C1> RemoveComponent(TypeExpression type)
        {
            AssertMutable();
            AssertNotRequired(type);
            _values.RemoveAt(_components.IndexOf(type));
            _components.Remove(type);
            return this;
        }

        #endregion


        /// <inheritdoc cref="EntityTemplate.Add{T}(T)"/>
        public EntityTemplate<C0, C1> Add<T>(T component) where T : notnull
        {
            var type = Comp<T>.Plain.Expression;
            return AddComponent(type, component);
        }

        /// <inheritdoc cref="EntityTemplate.Add{T}(Entity)"/>
        public EntityTemplate<C0, C1> Add<T>(Entity target) where T : notnull, new() => Add(new T(), target);


        /// <inheritdoc cref="EntityTemplate.Add{C}()"/>
        public EntityTemplate<C0, C1> Add<C>() where C : notnull, new() => Add(new C());


        /// <inheritdoc cref="EntityTemplate.Add{R}(R, Entity)"/>
        public EntityTemplate<C0, C1> Add<R>(R value, Entity relation) where R : notnull
        {
            var type = TypeExpression.Of<R>(relation);
            return AddComponent(type, value);
        }


        /// <inheritdoc cref="EntityTemplate.Add{T}(Link{T})"/>
        public EntityTemplate<C0, C1> Add<T>(Link<T> target) where T : class
        {
            var type = TypeExpression.Of<T>(target);
            return AddComponent(type, target.Object);
        }


        /// <inheritdoc cref="EntityTemplate.Remove{T}()"/>
        public EntityTemplate<C0, C1> Remove<T>() where T : notnull
        {
            var type = Comp<T>.Plain.Expression;
            return RemoveComponent(type);
        }

        /// <inheritdoc cref="EntityTemplate.Remove{T}(Entity)"/>
        public EntityTemplate<C0, C1> Remove<T>(Entity entity) where T : notnull
        {
            var type = TypeExpression.Of<T>(entity);
            return RemoveComponent(type);
        }

        /// <inheritdoc cref="EntityTemplate.Remove{L}(L)"/>
        public EntityTemplate<C0, C1> Remove<L>(L linkedObject) where L : class => Remove(Link<L>.With(linkedObject));

        /// <inheritdoc cref="EntityTemplate.Remove{L}(Link{L})"/>
        public EntityTemplate<C0, C1> Remove<L>(Link<L> link) where L : class
        {
            return RemoveComponent(link.TypeExpression);
        }

        /// <inheritdoc cref="EntityTemplate.Needs{C0}()"/>
        public EntityTemplate<C0, C1, C2> Needs<C2>() where C2 : notnull => Needs<C2>(Comp<C2>.Plain.Expression, Match.Plain);

        /// <inheritdoc cref="EntityTemplate.Needs{C0}(Entity)"/>
        public EntityTemplate<C0, C1, C2> Needs<C2>(Entity relation) where C2 : notnull => Needs<C2>(TypeExpression.Of<C2>(relation), Match.Relation(relation));

        private EntityTemplate<C0, C1, C2> Needs<C2>(TypeExpression expression, Match match) where C2 : notnull
        {
            AssertMutable();
            if (Array.IndexOf(_required, expression) >= 0)
                throw new InvalidOperationException($"Component {expression} is already a required Component of this template.");
            if (_components.Contains(expression))
                throw new InvalidOperationException($"Component {expression} is already configured on this template. Remove it first, or provide it at Spawn instead.");

            _consumed = true;
            var (components, values) = (_components, _values);
            _components = null!;
            _values = null!;
            return new EntityTemplate<C0, C1, C2>(_world, components, values, [.._required, expression], [.._matches, match]);
        }

        /// <summary>
        /// Spawns a single Entity with the configured Components and the provided required values.
        /// </summary>
        /// <param name="c0">value for the required Component C0</param>
        /// <param name="c1">value for the required Component C1</param>
        /// <returns>the spawned Entity</returns>
        public Entity Spawn(C0 c0, C1 c1)
        {
            Span<Entity> spawned = stackalloc Entity[1];
            Spawn(spawned, c0, c1);
            return spawned[0];
        }

        /// <summary>
        /// Spawns <c>count</c> Entities with the configured Components; the whole wave shares
        /// the provided required values.
        /// </summary>
        /// <param name="count">number of Entities to spawn</param>
        /// <param name="c0">value for the required Component C0</param>
        /// <param name="c1">value for the required Component C1</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1> Spawn(int count, C0 c0, C1 c1)
        {
            AssertMutable();
            if (count <= 0) return this;

            using var components = PooledList<TypeExpression>.Rent();
            using var values = PooledList<object>.Rent();
            components.AddRange(_components);
            values.AddRange(_values);
            components.Add(_required[0]);
            values.Add(c0);
            components.Add(_required[1]);
            values.Add(c1);
            _world.Spawn(count, components, values);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/> with the configured
        /// Components, writing their handles into the span; the whole wave shares the provided
        /// required values.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned</param>
        /// <param name="c0">value for the required Component C0</param>
        /// <param name="c1">value for the required Component C1</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1> Spawn(Span<Entity> destination, C0 c0, C1 c1)
        {
            AssertMutable();

            using var components = PooledList<TypeExpression>.Rent();
            using var values = PooledList<object>.Rent();
            components.AddRange(_components);
            values.AddRange(_values);
            components.Add(_required[0]);
            values.Add(c0);
            components.Add(_required[1]);
            values.Add(c1);
            _world.Spawn(destination, components, values);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/>, taking each Entity's
        /// required values from the value spans at the same index, and writing the minted handles
        /// into <paramref name="destination"/>.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned, and all value spans must match it</param>
        /// <param name="values0">per-Entity values for the required Component C0; length must equal the destination's</param>
        /// <param name="values1">per-Entity values for the required Component C1; length must equal the destination's</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1> Spawn(Span<Entity> destination, ReadOnlySpan<C0> values0, ReadOnlySpan<C1> values1)
        {
            AssertMutable();
            if (values0.Length != destination.Length) throw new ArgumentException($"Length ({values0.Length}) must equal destination.Length ({destination.Length})", nameof(values0));
            if (values1.Length != destination.Length) throw new ArgumentException($"Length ({values1.Length}) must equal destination.Length ({destination.Length})", nameof(values1));
            if (destination.IsEmpty) return this;

            // Broadcast-spawn the wave (lands contiguously, in destination order, per aspect
            // archetype), then blit each value span straight into its storage slice. (no boxing)
            Spawn(destination, values0[0], values1[0]);
            var slice0 = _world.ContiguousSlice<C0>(destination[0], _matches[0], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice0[^1], ref destination[^1].Ref<C0>(_matches[0])), "Spawn wave is not contiguous in Component storage.");
            values0.CopyTo(slice0);
            var slice1 = _world.ContiguousSlice<C1>(destination[0], _matches[1], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice1[^1], ref destination[^1].Ref<C1>(_matches[1])), "Spawn wave is not contiguous in Component storage.");
            values1.CopyTo(slice1);
            return this;
        }

        /// <summary>
        /// Spawns <c>count</c> Entities with the configured Components, calling <paramref name="factory"/>
        /// with each Entity's index to produce its required values.
        /// </summary>
        /// <param name="count">number of Entities to spawn</param>
        /// <param name="factory">produces the required values for the Entity at each index</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1> Spawn(int count, Func<int, (C0, C1)> factory)
        {
            AssertMutable();
            ArgumentNullException.ThrowIfNull(factory);
            if (count <= 0) return this;

            var entities = ArrayPool<Entity>.Shared.Rent(count);
            Spawn(entities.AsSpan(0, count), factory);
            ArrayPool<Entity>.Shared.Return(entities);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/>, calling <paramref name="factory"/>
        /// with each Entity's index to produce its required values, and writing the minted handles
        /// into <paramref name="destination"/>.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned</param>
        /// <param name="factory">produces the required values for the Entity at each index</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1> Spawn(Span<Entity> destination, Func<int, (C0, C1)> factory)
        {
            AssertMutable();
            ArgumentNullException.ThrowIfNull(factory);
            if (destination.IsEmpty) return this;

            var count = destination.Length;
            var rented0 = ArrayPool<C0>.Shared.Rent(count);
            var rented1 = ArrayPool<C1>.Shared.Rent(count);
            for (var i = 0; i < count; i++)
            {
                var (c0, c1) = factory(i);
                rented0[i] = c0;
                rented1[i] = c1;
            }
            Spawn(destination, rented0.AsSpan(0, count), rented1.AsSpan(0, count));
            ArrayPool<C0>.Shared.Return(rented0, RuntimeHelpers.IsReferenceOrContainsReferences<C0>());
            ArrayPool<C1>.Shared.Return(rented1, RuntimeHelpers.IsReferenceOrContainsReferences<C1>());
            return this;
        }

        /// <inheritdoc />
        public void Dispose()
        {
            if (_consumed) return; // ownership moved to a wider template via Needs

            ObjectDisposedException.ThrowIf(_disposed, this);
            _disposed = true;

            _components.Dispose();
            _components = null!;

            _values.Dispose();
            _values = null!;
        }
    }

    /// <summary>
    /// An Entity template with 3 required Components, declared via <c>Needs</c>.
    /// Values for the required Components must be provided at <c>Spawn</c>, enforced at compile time.
    /// </summary>
    /// <remarks>
    /// Call any <c>Spawn</c> overload to actually spawn Entities.
    /// </remarks>
    public sealed class EntityTemplate<C0, C1, C2> : IDisposable, IAddRemove<EntityTemplate<C0, C1, C2>>
        where C0 : notnull
        where C1 : notnull
        where C2 : notnull
    {
        #region Internals

        private readonly World _world;

        private PooledList<TypeExpression> _components;
        private PooledList<object> _values;

        // Type Expressions and Match terms of the required Components, index i belongs to Ci.
        private readonly TypeExpression[] _required;
        private readonly Match[] _matches;

        private bool _disposed;
        private bool _consumed;

        internal EntityTemplate(World world, PooledList<TypeExpression> components, PooledList<object> values, TypeExpression[] required, Match[] matches)
        {
            _world = world;
            _components = components;
            _values = values;
            _required = required;
            _matches = matches;
        }

        private void AssertMutable() => ObjectDisposedException.ThrowIf(_disposed || _consumed, this);

        private void AssertNotRequired(TypeExpression type)
        {
            if (Array.IndexOf(_required, type) >= 0)
                throw new InvalidOperationException($"Component {type} is a required Component of this template and must be provided at Spawn.");
        }

        private EntityTemplate<C0, C1, C2> AddComponent(TypeExpression type, object value)
        {
            AssertMutable();
            AssertNotRequired(type);
            if (_components.Contains(type))
            {
                // replace existing value
                _values[_components.IndexOf(type)] = value;
            }
            else
            {
                // add new value
                _components.Add(type);
                _values.Add(value);
            }
            return this;
        }

        private EntityTemplate<C0, C1, C2> RemoveComponent(TypeExpression type)
        {
            AssertMutable();
            AssertNotRequired(type);
            _values.RemoveAt(_components.IndexOf(type));
            _components.Remove(type);
            return this;
        }

        #endregion


        /// <inheritdoc cref="EntityTemplate.Add{T}(T)"/>
        public EntityTemplate<C0, C1, C2> Add<T>(T component) where T : notnull
        {
            var type = Comp<T>.Plain.Expression;
            return AddComponent(type, component);
        }

        /// <inheritdoc cref="EntityTemplate.Add{T}(Entity)"/>
        public EntityTemplate<C0, C1, C2> Add<T>(Entity target) where T : notnull, new() => Add(new T(), target);


        /// <inheritdoc cref="EntityTemplate.Add{C}()"/>
        public EntityTemplate<C0, C1, C2> Add<C>() where C : notnull, new() => Add(new C());


        /// <inheritdoc cref="EntityTemplate.Add{R}(R, Entity)"/>
        public EntityTemplate<C0, C1, C2> Add<R>(R value, Entity relation) where R : notnull
        {
            var type = TypeExpression.Of<R>(relation);
            return AddComponent(type, value);
        }


        /// <inheritdoc cref="EntityTemplate.Add{T}(Link{T})"/>
        public EntityTemplate<C0, C1, C2> Add<T>(Link<T> target) where T : class
        {
            var type = TypeExpression.Of<T>(target);
            return AddComponent(type, target.Object);
        }


        /// <inheritdoc cref="EntityTemplate.Remove{T}()"/>
        public EntityTemplate<C0, C1, C2> Remove<T>() where T : notnull
        {
            var type = Comp<T>.Plain.Expression;
            return RemoveComponent(type);
        }

        /// <inheritdoc cref="EntityTemplate.Remove{T}(Entity)"/>
        public EntityTemplate<C0, C1, C2> Remove<T>(Entity entity) where T : notnull
        {
            var type = TypeExpression.Of<T>(entity);
            return RemoveComponent(type);
        }

        /// <inheritdoc cref="EntityTemplate.Remove{L}(L)"/>
        public EntityTemplate<C0, C1, C2> Remove<L>(L linkedObject) where L : class => Remove(Link<L>.With(linkedObject));

        /// <inheritdoc cref="EntityTemplate.Remove{L}(Link{L})"/>
        public EntityTemplate<C0, C1, C2> Remove<L>(Link<L> link) where L : class
        {
            return RemoveComponent(link.TypeExpression);
        }

        /// <inheritdoc cref="EntityTemplate.Needs{C0}()"/>
        public EntityTemplate<C0, C1, C2, C3> Needs<C3>() where C3 : notnull => Needs<C3>(Comp<C3>.Plain.Expression, Match.Plain);

        /// <inheritdoc cref="EntityTemplate.Needs{C0}(Entity)"/>
        public EntityTemplate<C0, C1, C2, C3> Needs<C3>(Entity relation) where C3 : notnull => Needs<C3>(TypeExpression.Of<C3>(relation), Match.Relation(relation));

        private EntityTemplate<C0, C1, C2, C3> Needs<C3>(TypeExpression expression, Match match) where C3 : notnull
        {
            AssertMutable();
            if (Array.IndexOf(_required, expression) >= 0)
                throw new InvalidOperationException($"Component {expression} is already a required Component of this template.");
            if (_components.Contains(expression))
                throw new InvalidOperationException($"Component {expression} is already configured on this template. Remove it first, or provide it at Spawn instead.");

            _consumed = true;
            var (components, values) = (_components, _values);
            _components = null!;
            _values = null!;
            return new EntityTemplate<C0, C1, C2, C3>(_world, components, values, [.._required, expression], [.._matches, match]);
        }

        /// <summary>
        /// Spawns a single Entity with the configured Components and the provided required values.
        /// </summary>
        /// <param name="c0">value for the required Component C0</param>
        /// <param name="c1">value for the required Component C1</param>
        /// <param name="c2">value for the required Component C2</param>
        /// <returns>the spawned Entity</returns>
        public Entity Spawn(C0 c0, C1 c1, C2 c2)
        {
            Span<Entity> spawned = stackalloc Entity[1];
            Spawn(spawned, c0, c1, c2);
            return spawned[0];
        }

        /// <summary>
        /// Spawns <c>count</c> Entities with the configured Components; the whole wave shares
        /// the provided required values.
        /// </summary>
        /// <param name="count">number of Entities to spawn</param>
        /// <param name="c0">value for the required Component C0</param>
        /// <param name="c1">value for the required Component C1</param>
        /// <param name="c2">value for the required Component C2</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2> Spawn(int count, C0 c0, C1 c1, C2 c2)
        {
            AssertMutable();
            if (count <= 0) return this;

            using var components = PooledList<TypeExpression>.Rent();
            using var values = PooledList<object>.Rent();
            components.AddRange(_components);
            values.AddRange(_values);
            components.Add(_required[0]);
            values.Add(c0);
            components.Add(_required[1]);
            values.Add(c1);
            components.Add(_required[2]);
            values.Add(c2);
            _world.Spawn(count, components, values);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/> with the configured
        /// Components, writing their handles into the span; the whole wave shares the provided
        /// required values.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned</param>
        /// <param name="c0">value for the required Component C0</param>
        /// <param name="c1">value for the required Component C1</param>
        /// <param name="c2">value for the required Component C2</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2> Spawn(Span<Entity> destination, C0 c0, C1 c1, C2 c2)
        {
            AssertMutable();

            using var components = PooledList<TypeExpression>.Rent();
            using var values = PooledList<object>.Rent();
            components.AddRange(_components);
            values.AddRange(_values);
            components.Add(_required[0]);
            values.Add(c0);
            components.Add(_required[1]);
            values.Add(c1);
            components.Add(_required[2]);
            values.Add(c2);
            _world.Spawn(destination, components, values);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/>, taking each Entity's
        /// required values from the value spans at the same index, and writing the minted handles
        /// into <paramref name="destination"/>.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned, and all value spans must match it</param>
        /// <param name="values0">per-Entity values for the required Component C0; length must equal the destination's</param>
        /// <param name="values1">per-Entity values for the required Component C1; length must equal the destination's</param>
        /// <param name="values2">per-Entity values for the required Component C2; length must equal the destination's</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2> Spawn(Span<Entity> destination, ReadOnlySpan<C0> values0, ReadOnlySpan<C1> values1, ReadOnlySpan<C2> values2)
        {
            AssertMutable();
            if (values0.Length != destination.Length) throw new ArgumentException($"Length ({values0.Length}) must equal destination.Length ({destination.Length})", nameof(values0));
            if (values1.Length != destination.Length) throw new ArgumentException($"Length ({values1.Length}) must equal destination.Length ({destination.Length})", nameof(values1));
            if (values2.Length != destination.Length) throw new ArgumentException($"Length ({values2.Length}) must equal destination.Length ({destination.Length})", nameof(values2));
            if (destination.IsEmpty) return this;

            // Broadcast-spawn the wave (lands contiguously, in destination order, per aspect
            // archetype), then blit each value span straight into its storage slice. (no boxing)
            Spawn(destination, values0[0], values1[0], values2[0]);
            var slice0 = _world.ContiguousSlice<C0>(destination[0], _matches[0], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice0[^1], ref destination[^1].Ref<C0>(_matches[0])), "Spawn wave is not contiguous in Component storage.");
            values0.CopyTo(slice0);
            var slice1 = _world.ContiguousSlice<C1>(destination[0], _matches[1], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice1[^1], ref destination[^1].Ref<C1>(_matches[1])), "Spawn wave is not contiguous in Component storage.");
            values1.CopyTo(slice1);
            var slice2 = _world.ContiguousSlice<C2>(destination[0], _matches[2], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice2[^1], ref destination[^1].Ref<C2>(_matches[2])), "Spawn wave is not contiguous in Component storage.");
            values2.CopyTo(slice2);
            return this;
        }

        /// <summary>
        /// Spawns <c>count</c> Entities with the configured Components, calling <paramref name="factory"/>
        /// with each Entity's index to produce its required values.
        /// </summary>
        /// <param name="count">number of Entities to spawn</param>
        /// <param name="factory">produces the required values for the Entity at each index</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2> Spawn(int count, Func<int, (C0, C1, C2)> factory)
        {
            AssertMutable();
            ArgumentNullException.ThrowIfNull(factory);
            if (count <= 0) return this;

            var entities = ArrayPool<Entity>.Shared.Rent(count);
            Spawn(entities.AsSpan(0, count), factory);
            ArrayPool<Entity>.Shared.Return(entities);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/>, calling <paramref name="factory"/>
        /// with each Entity's index to produce its required values, and writing the minted handles
        /// into <paramref name="destination"/>.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned</param>
        /// <param name="factory">produces the required values for the Entity at each index</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2> Spawn(Span<Entity> destination, Func<int, (C0, C1, C2)> factory)
        {
            AssertMutable();
            ArgumentNullException.ThrowIfNull(factory);
            if (destination.IsEmpty) return this;

            var count = destination.Length;
            var rented0 = ArrayPool<C0>.Shared.Rent(count);
            var rented1 = ArrayPool<C1>.Shared.Rent(count);
            var rented2 = ArrayPool<C2>.Shared.Rent(count);
            for (var i = 0; i < count; i++)
            {
                var (c0, c1, c2) = factory(i);
                rented0[i] = c0;
                rented1[i] = c1;
                rented2[i] = c2;
            }
            Spawn(destination, rented0.AsSpan(0, count), rented1.AsSpan(0, count), rented2.AsSpan(0, count));
            ArrayPool<C0>.Shared.Return(rented0, RuntimeHelpers.IsReferenceOrContainsReferences<C0>());
            ArrayPool<C1>.Shared.Return(rented1, RuntimeHelpers.IsReferenceOrContainsReferences<C1>());
            ArrayPool<C2>.Shared.Return(rented2, RuntimeHelpers.IsReferenceOrContainsReferences<C2>());
            return this;
        }

        /// <inheritdoc />
        public void Dispose()
        {
            if (_consumed) return; // ownership moved to a wider template via Needs

            ObjectDisposedException.ThrowIf(_disposed, this);
            _disposed = true;

            _components.Dispose();
            _components = null!;

            _values.Dispose();
            _values = null!;
        }
    }

    /// <summary>
    /// An Entity template with 4 required Components, declared via <c>Needs</c>.
    /// Values for the required Components must be provided at <c>Spawn</c>, enforced at compile time.
    /// </summary>
    /// <remarks>
    /// Call any <c>Spawn</c> overload to actually spawn Entities.
    /// </remarks>
    public sealed class EntityTemplate<C0, C1, C2, C3> : IDisposable, IAddRemove<EntityTemplate<C0, C1, C2, C3>>
        where C0 : notnull
        where C1 : notnull
        where C2 : notnull
        where C3 : notnull
    {
        #region Internals

        private readonly World _world;

        private PooledList<TypeExpression> _components;
        private PooledList<object> _values;

        // Type Expressions and Match terms of the required Components, index i belongs to Ci.
        private readonly TypeExpression[] _required;
        private readonly Match[] _matches;

        private bool _disposed;
        private bool _consumed;

        internal EntityTemplate(World world, PooledList<TypeExpression> components, PooledList<object> values, TypeExpression[] required, Match[] matches)
        {
            _world = world;
            _components = components;
            _values = values;
            _required = required;
            _matches = matches;
        }

        private void AssertMutable() => ObjectDisposedException.ThrowIf(_disposed || _consumed, this);

        private void AssertNotRequired(TypeExpression type)
        {
            if (Array.IndexOf(_required, type) >= 0)
                throw new InvalidOperationException($"Component {type} is a required Component of this template and must be provided at Spawn.");
        }

        private EntityTemplate<C0, C1, C2, C3> AddComponent(TypeExpression type, object value)
        {
            AssertMutable();
            AssertNotRequired(type);
            if (_components.Contains(type))
            {
                // replace existing value
                _values[_components.IndexOf(type)] = value;
            }
            else
            {
                // add new value
                _components.Add(type);
                _values.Add(value);
            }
            return this;
        }

        private EntityTemplate<C0, C1, C2, C3> RemoveComponent(TypeExpression type)
        {
            AssertMutable();
            AssertNotRequired(type);
            _values.RemoveAt(_components.IndexOf(type));
            _components.Remove(type);
            return this;
        }

        #endregion


        /// <inheritdoc cref="EntityTemplate.Add{T}(T)"/>
        public EntityTemplate<C0, C1, C2, C3> Add<T>(T component) where T : notnull
        {
            var type = Comp<T>.Plain.Expression;
            return AddComponent(type, component);
        }

        /// <inheritdoc cref="EntityTemplate.Add{T}(Entity)"/>
        public EntityTemplate<C0, C1, C2, C3> Add<T>(Entity target) where T : notnull, new() => Add(new T(), target);


        /// <inheritdoc cref="EntityTemplate.Add{C}()"/>
        public EntityTemplate<C0, C1, C2, C3> Add<C>() where C : notnull, new() => Add(new C());


        /// <inheritdoc cref="EntityTemplate.Add{R}(R, Entity)"/>
        public EntityTemplate<C0, C1, C2, C3> Add<R>(R value, Entity relation) where R : notnull
        {
            var type = TypeExpression.Of<R>(relation);
            return AddComponent(type, value);
        }


        /// <inheritdoc cref="EntityTemplate.Add{T}(Link{T})"/>
        public EntityTemplate<C0, C1, C2, C3> Add<T>(Link<T> target) where T : class
        {
            var type = TypeExpression.Of<T>(target);
            return AddComponent(type, target.Object);
        }


        /// <inheritdoc cref="EntityTemplate.Remove{T}()"/>
        public EntityTemplate<C0, C1, C2, C3> Remove<T>() where T : notnull
        {
            var type = Comp<T>.Plain.Expression;
            return RemoveComponent(type);
        }

        /// <inheritdoc cref="EntityTemplate.Remove{T}(Entity)"/>
        public EntityTemplate<C0, C1, C2, C3> Remove<T>(Entity entity) where T : notnull
        {
            var type = TypeExpression.Of<T>(entity);
            return RemoveComponent(type);
        }

        /// <inheritdoc cref="EntityTemplate.Remove{L}(L)"/>
        public EntityTemplate<C0, C1, C2, C3> Remove<L>(L linkedObject) where L : class => Remove(Link<L>.With(linkedObject));

        /// <inheritdoc cref="EntityTemplate.Remove{L}(Link{L})"/>
        public EntityTemplate<C0, C1, C2, C3> Remove<L>(Link<L> link) where L : class
        {
            return RemoveComponent(link.TypeExpression);
        }

        /// <inheritdoc cref="EntityTemplate.Needs{C0}()"/>
        public EntityTemplate<C0, C1, C2, C3, C4> Needs<C4>() where C4 : notnull => Needs<C4>(Comp<C4>.Plain.Expression, Match.Plain);

        /// <inheritdoc cref="EntityTemplate.Needs{C0}(Entity)"/>
        public EntityTemplate<C0, C1, C2, C3, C4> Needs<C4>(Entity relation) where C4 : notnull => Needs<C4>(TypeExpression.Of<C4>(relation), Match.Relation(relation));

        private EntityTemplate<C0, C1, C2, C3, C4> Needs<C4>(TypeExpression expression, Match match) where C4 : notnull
        {
            AssertMutable();
            if (Array.IndexOf(_required, expression) >= 0)
                throw new InvalidOperationException($"Component {expression} is already a required Component of this template.");
            if (_components.Contains(expression))
                throw new InvalidOperationException($"Component {expression} is already configured on this template. Remove it first, or provide it at Spawn instead.");

            _consumed = true;
            var (components, values) = (_components, _values);
            _components = null!;
            _values = null!;
            return new EntityTemplate<C0, C1, C2, C3, C4>(_world, components, values, [.._required, expression], [.._matches, match]);
        }

        /// <summary>
        /// Spawns a single Entity with the configured Components and the provided required values.
        /// </summary>
        /// <param name="c0">value for the required Component C0</param>
        /// <param name="c1">value for the required Component C1</param>
        /// <param name="c2">value for the required Component C2</param>
        /// <param name="c3">value for the required Component C3</param>
        /// <returns>the spawned Entity</returns>
        public Entity Spawn(C0 c0, C1 c1, C2 c2, C3 c3)
        {
            Span<Entity> spawned = stackalloc Entity[1];
            Spawn(spawned, c0, c1, c2, c3);
            return spawned[0];
        }

        /// <summary>
        /// Spawns <c>count</c> Entities with the configured Components; the whole wave shares
        /// the provided required values.
        /// </summary>
        /// <param name="count">number of Entities to spawn</param>
        /// <param name="c0">value for the required Component C0</param>
        /// <param name="c1">value for the required Component C1</param>
        /// <param name="c2">value for the required Component C2</param>
        /// <param name="c3">value for the required Component C3</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2, C3> Spawn(int count, C0 c0, C1 c1, C2 c2, C3 c3)
        {
            AssertMutable();
            if (count <= 0) return this;

            using var components = PooledList<TypeExpression>.Rent();
            using var values = PooledList<object>.Rent();
            components.AddRange(_components);
            values.AddRange(_values);
            components.Add(_required[0]);
            values.Add(c0);
            components.Add(_required[1]);
            values.Add(c1);
            components.Add(_required[2]);
            values.Add(c2);
            components.Add(_required[3]);
            values.Add(c3);
            _world.Spawn(count, components, values);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/> with the configured
        /// Components, writing their handles into the span; the whole wave shares the provided
        /// required values.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned</param>
        /// <param name="c0">value for the required Component C0</param>
        /// <param name="c1">value for the required Component C1</param>
        /// <param name="c2">value for the required Component C2</param>
        /// <param name="c3">value for the required Component C3</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2, C3> Spawn(Span<Entity> destination, C0 c0, C1 c1, C2 c2, C3 c3)
        {
            AssertMutable();

            using var components = PooledList<TypeExpression>.Rent();
            using var values = PooledList<object>.Rent();
            components.AddRange(_components);
            values.AddRange(_values);
            components.Add(_required[0]);
            values.Add(c0);
            components.Add(_required[1]);
            values.Add(c1);
            components.Add(_required[2]);
            values.Add(c2);
            components.Add(_required[3]);
            values.Add(c3);
            _world.Spawn(destination, components, values);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/>, taking each Entity's
        /// required values from the value spans at the same index, and writing the minted handles
        /// into <paramref name="destination"/>.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned, and all value spans must match it</param>
        /// <param name="values0">per-Entity values for the required Component C0; length must equal the destination's</param>
        /// <param name="values1">per-Entity values for the required Component C1; length must equal the destination's</param>
        /// <param name="values2">per-Entity values for the required Component C2; length must equal the destination's</param>
        /// <param name="values3">per-Entity values for the required Component C3; length must equal the destination's</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2, C3> Spawn(Span<Entity> destination, ReadOnlySpan<C0> values0, ReadOnlySpan<C1> values1, ReadOnlySpan<C2> values2, ReadOnlySpan<C3> values3)
        {
            AssertMutable();
            if (values0.Length != destination.Length) throw new ArgumentException($"Length ({values0.Length}) must equal destination.Length ({destination.Length})", nameof(values0));
            if (values1.Length != destination.Length) throw new ArgumentException($"Length ({values1.Length}) must equal destination.Length ({destination.Length})", nameof(values1));
            if (values2.Length != destination.Length) throw new ArgumentException($"Length ({values2.Length}) must equal destination.Length ({destination.Length})", nameof(values2));
            if (values3.Length != destination.Length) throw new ArgumentException($"Length ({values3.Length}) must equal destination.Length ({destination.Length})", nameof(values3));
            if (destination.IsEmpty) return this;

            // Broadcast-spawn the wave (lands contiguously, in destination order, per aspect
            // archetype), then blit each value span straight into its storage slice. (no boxing)
            Spawn(destination, values0[0], values1[0], values2[0], values3[0]);
            var slice0 = _world.ContiguousSlice<C0>(destination[0], _matches[0], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice0[^1], ref destination[^1].Ref<C0>(_matches[0])), "Spawn wave is not contiguous in Component storage.");
            values0.CopyTo(slice0);
            var slice1 = _world.ContiguousSlice<C1>(destination[0], _matches[1], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice1[^1], ref destination[^1].Ref<C1>(_matches[1])), "Spawn wave is not contiguous in Component storage.");
            values1.CopyTo(slice1);
            var slice2 = _world.ContiguousSlice<C2>(destination[0], _matches[2], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice2[^1], ref destination[^1].Ref<C2>(_matches[2])), "Spawn wave is not contiguous in Component storage.");
            values2.CopyTo(slice2);
            var slice3 = _world.ContiguousSlice<C3>(destination[0], _matches[3], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice3[^1], ref destination[^1].Ref<C3>(_matches[3])), "Spawn wave is not contiguous in Component storage.");
            values3.CopyTo(slice3);
            return this;
        }

        /// <summary>
        /// Spawns <c>count</c> Entities with the configured Components, calling <paramref name="factory"/>
        /// with each Entity's index to produce its required values.
        /// </summary>
        /// <param name="count">number of Entities to spawn</param>
        /// <param name="factory">produces the required values for the Entity at each index</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2, C3> Spawn(int count, Func<int, (C0, C1, C2, C3)> factory)
        {
            AssertMutable();
            ArgumentNullException.ThrowIfNull(factory);
            if (count <= 0) return this;

            var entities = ArrayPool<Entity>.Shared.Rent(count);
            Spawn(entities.AsSpan(0, count), factory);
            ArrayPool<Entity>.Shared.Return(entities);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/>, calling <paramref name="factory"/>
        /// with each Entity's index to produce its required values, and writing the minted handles
        /// into <paramref name="destination"/>.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned</param>
        /// <param name="factory">produces the required values for the Entity at each index</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2, C3> Spawn(Span<Entity> destination, Func<int, (C0, C1, C2, C3)> factory)
        {
            AssertMutable();
            ArgumentNullException.ThrowIfNull(factory);
            if (destination.IsEmpty) return this;

            var count = destination.Length;
            var rented0 = ArrayPool<C0>.Shared.Rent(count);
            var rented1 = ArrayPool<C1>.Shared.Rent(count);
            var rented2 = ArrayPool<C2>.Shared.Rent(count);
            var rented3 = ArrayPool<C3>.Shared.Rent(count);
            for (var i = 0; i < count; i++)
            {
                var (c0, c1, c2, c3) = factory(i);
                rented0[i] = c0;
                rented1[i] = c1;
                rented2[i] = c2;
                rented3[i] = c3;
            }
            Spawn(destination, rented0.AsSpan(0, count), rented1.AsSpan(0, count), rented2.AsSpan(0, count), rented3.AsSpan(0, count));
            ArrayPool<C0>.Shared.Return(rented0, RuntimeHelpers.IsReferenceOrContainsReferences<C0>());
            ArrayPool<C1>.Shared.Return(rented1, RuntimeHelpers.IsReferenceOrContainsReferences<C1>());
            ArrayPool<C2>.Shared.Return(rented2, RuntimeHelpers.IsReferenceOrContainsReferences<C2>());
            ArrayPool<C3>.Shared.Return(rented3, RuntimeHelpers.IsReferenceOrContainsReferences<C3>());
            return this;
        }

        /// <inheritdoc />
        public void Dispose()
        {
            if (_consumed) return; // ownership moved to a wider template via Needs

            ObjectDisposedException.ThrowIf(_disposed, this);
            _disposed = true;

            _components.Dispose();
            _components = null!;

            _values.Dispose();
            _values = null!;
        }
    }

    /// <summary>
    /// An Entity template with 5 required Components, declared via <c>Needs</c>.
    /// Values for the required Components must be provided at <c>Spawn</c>, enforced at compile time.
    /// </summary>
    /// <remarks>
    /// Call any <c>Spawn</c> overload to actually spawn Entities.
    /// </remarks>
    public sealed class EntityTemplate<C0, C1, C2, C3, C4> : IDisposable, IAddRemove<EntityTemplate<C0, C1, C2, C3, C4>>
        where C0 : notnull
        where C1 : notnull
        where C2 : notnull
        where C3 : notnull
        where C4 : notnull
    {
        #region Internals

        private readonly World _world;

        private PooledList<TypeExpression> _components;
        private PooledList<object> _values;

        // Type Expressions and Match terms of the required Components, index i belongs to Ci.
        private readonly TypeExpression[] _required;
        private readonly Match[] _matches;

        private bool _disposed;
        private bool _consumed;

        internal EntityTemplate(World world, PooledList<TypeExpression> components, PooledList<object> values, TypeExpression[] required, Match[] matches)
        {
            _world = world;
            _components = components;
            _values = values;
            _required = required;
            _matches = matches;
        }

        private void AssertMutable() => ObjectDisposedException.ThrowIf(_disposed || _consumed, this);

        private void AssertNotRequired(TypeExpression type)
        {
            if (Array.IndexOf(_required, type) >= 0)
                throw new InvalidOperationException($"Component {type} is a required Component of this template and must be provided at Spawn.");
        }

        private EntityTemplate<C0, C1, C2, C3, C4> AddComponent(TypeExpression type, object value)
        {
            AssertMutable();
            AssertNotRequired(type);
            if (_components.Contains(type))
            {
                // replace existing value
                _values[_components.IndexOf(type)] = value;
            }
            else
            {
                // add new value
                _components.Add(type);
                _values.Add(value);
            }
            return this;
        }

        private EntityTemplate<C0, C1, C2, C3, C4> RemoveComponent(TypeExpression type)
        {
            AssertMutable();
            AssertNotRequired(type);
            _values.RemoveAt(_components.IndexOf(type));
            _components.Remove(type);
            return this;
        }

        #endregion


        /// <inheritdoc cref="EntityTemplate.Add{T}(T)"/>
        public EntityTemplate<C0, C1, C2, C3, C4> Add<T>(T component) where T : notnull
        {
            var type = Comp<T>.Plain.Expression;
            return AddComponent(type, component);
        }

        /// <inheritdoc cref="EntityTemplate.Add{T}(Entity)"/>
        public EntityTemplate<C0, C1, C2, C3, C4> Add<T>(Entity target) where T : notnull, new() => Add(new T(), target);


        /// <inheritdoc cref="EntityTemplate.Add{C}()"/>
        public EntityTemplate<C0, C1, C2, C3, C4> Add<C>() where C : notnull, new() => Add(new C());


        /// <inheritdoc cref="EntityTemplate.Add{R}(R, Entity)"/>
        public EntityTemplate<C0, C1, C2, C3, C4> Add<R>(R value, Entity relation) where R : notnull
        {
            var type = TypeExpression.Of<R>(relation);
            return AddComponent(type, value);
        }


        /// <inheritdoc cref="EntityTemplate.Add{T}(Link{T})"/>
        public EntityTemplate<C0, C1, C2, C3, C4> Add<T>(Link<T> target) where T : class
        {
            var type = TypeExpression.Of<T>(target);
            return AddComponent(type, target.Object);
        }


        /// <inheritdoc cref="EntityTemplate.Remove{T}()"/>
        public EntityTemplate<C0, C1, C2, C3, C4> Remove<T>() where T : notnull
        {
            var type = Comp<T>.Plain.Expression;
            return RemoveComponent(type);
        }

        /// <inheritdoc cref="EntityTemplate.Remove{T}(Entity)"/>
        public EntityTemplate<C0, C1, C2, C3, C4> Remove<T>(Entity entity) where T : notnull
        {
            var type = TypeExpression.Of<T>(entity);
            return RemoveComponent(type);
        }

        /// <inheritdoc cref="EntityTemplate.Remove{L}(L)"/>
        public EntityTemplate<C0, C1, C2, C3, C4> Remove<L>(L linkedObject) where L : class => Remove(Link<L>.With(linkedObject));

        /// <inheritdoc cref="EntityTemplate.Remove{L}(Link{L})"/>
        public EntityTemplate<C0, C1, C2, C3, C4> Remove<L>(Link<L> link) where L : class
        {
            return RemoveComponent(link.TypeExpression);
        }

        /// <inheritdoc cref="EntityTemplate.Needs{C0}()"/>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Needs<C5>() where C5 : notnull => Needs<C5>(Comp<C5>.Plain.Expression, Match.Plain);

        /// <inheritdoc cref="EntityTemplate.Needs{C0}(Entity)"/>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Needs<C5>(Entity relation) where C5 : notnull => Needs<C5>(TypeExpression.Of<C5>(relation), Match.Relation(relation));

        private EntityTemplate<C0, C1, C2, C3, C4, C5> Needs<C5>(TypeExpression expression, Match match) where C5 : notnull
        {
            AssertMutable();
            if (Array.IndexOf(_required, expression) >= 0)
                throw new InvalidOperationException($"Component {expression} is already a required Component of this template.");
            if (_components.Contains(expression))
                throw new InvalidOperationException($"Component {expression} is already configured on this template. Remove it first, or provide it at Spawn instead.");

            _consumed = true;
            var (components, values) = (_components, _values);
            _components = null!;
            _values = null!;
            return new EntityTemplate<C0, C1, C2, C3, C4, C5>(_world, components, values, [.._required, expression], [.._matches, match]);
        }

        /// <summary>
        /// Spawns a single Entity with the configured Components and the provided required values.
        /// </summary>
        /// <param name="c0">value for the required Component C0</param>
        /// <param name="c1">value for the required Component C1</param>
        /// <param name="c2">value for the required Component C2</param>
        /// <param name="c3">value for the required Component C3</param>
        /// <param name="c4">value for the required Component C4</param>
        /// <returns>the spawned Entity</returns>
        public Entity Spawn(C0 c0, C1 c1, C2 c2, C3 c3, C4 c4)
        {
            Span<Entity> spawned = stackalloc Entity[1];
            Spawn(spawned, c0, c1, c2, c3, c4);
            return spawned[0];
        }

        /// <summary>
        /// Spawns <c>count</c> Entities with the configured Components; the whole wave shares
        /// the provided required values.
        /// </summary>
        /// <param name="count">number of Entities to spawn</param>
        /// <param name="c0">value for the required Component C0</param>
        /// <param name="c1">value for the required Component C1</param>
        /// <param name="c2">value for the required Component C2</param>
        /// <param name="c3">value for the required Component C3</param>
        /// <param name="c4">value for the required Component C4</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2, C3, C4> Spawn(int count, C0 c0, C1 c1, C2 c2, C3 c3, C4 c4)
        {
            AssertMutable();
            if (count <= 0) return this;

            using var components = PooledList<TypeExpression>.Rent();
            using var values = PooledList<object>.Rent();
            components.AddRange(_components);
            values.AddRange(_values);
            components.Add(_required[0]);
            values.Add(c0);
            components.Add(_required[1]);
            values.Add(c1);
            components.Add(_required[2]);
            values.Add(c2);
            components.Add(_required[3]);
            values.Add(c3);
            components.Add(_required[4]);
            values.Add(c4);
            _world.Spawn(count, components, values);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/> with the configured
        /// Components, writing their handles into the span; the whole wave shares the provided
        /// required values.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned</param>
        /// <param name="c0">value for the required Component C0</param>
        /// <param name="c1">value for the required Component C1</param>
        /// <param name="c2">value for the required Component C2</param>
        /// <param name="c3">value for the required Component C3</param>
        /// <param name="c4">value for the required Component C4</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2, C3, C4> Spawn(Span<Entity> destination, C0 c0, C1 c1, C2 c2, C3 c3, C4 c4)
        {
            AssertMutable();

            using var components = PooledList<TypeExpression>.Rent();
            using var values = PooledList<object>.Rent();
            components.AddRange(_components);
            values.AddRange(_values);
            components.Add(_required[0]);
            values.Add(c0);
            components.Add(_required[1]);
            values.Add(c1);
            components.Add(_required[2]);
            values.Add(c2);
            components.Add(_required[3]);
            values.Add(c3);
            components.Add(_required[4]);
            values.Add(c4);
            _world.Spawn(destination, components, values);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/>, taking each Entity's
        /// required values from the value spans at the same index, and writing the minted handles
        /// into <paramref name="destination"/>.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned, and all value spans must match it</param>
        /// <param name="values0">per-Entity values for the required Component C0; length must equal the destination's</param>
        /// <param name="values1">per-Entity values for the required Component C1; length must equal the destination's</param>
        /// <param name="values2">per-Entity values for the required Component C2; length must equal the destination's</param>
        /// <param name="values3">per-Entity values for the required Component C3; length must equal the destination's</param>
        /// <param name="values4">per-Entity values for the required Component C4; length must equal the destination's</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2, C3, C4> Spawn(Span<Entity> destination, ReadOnlySpan<C0> values0, ReadOnlySpan<C1> values1, ReadOnlySpan<C2> values2, ReadOnlySpan<C3> values3, ReadOnlySpan<C4> values4)
        {
            AssertMutable();
            if (values0.Length != destination.Length) throw new ArgumentException($"Length ({values0.Length}) must equal destination.Length ({destination.Length})", nameof(values0));
            if (values1.Length != destination.Length) throw new ArgumentException($"Length ({values1.Length}) must equal destination.Length ({destination.Length})", nameof(values1));
            if (values2.Length != destination.Length) throw new ArgumentException($"Length ({values2.Length}) must equal destination.Length ({destination.Length})", nameof(values2));
            if (values3.Length != destination.Length) throw new ArgumentException($"Length ({values3.Length}) must equal destination.Length ({destination.Length})", nameof(values3));
            if (values4.Length != destination.Length) throw new ArgumentException($"Length ({values4.Length}) must equal destination.Length ({destination.Length})", nameof(values4));
            if (destination.IsEmpty) return this;

            // Broadcast-spawn the wave (lands contiguously, in destination order, per aspect
            // archetype), then blit each value span straight into its storage slice. (no boxing)
            Spawn(destination, values0[0], values1[0], values2[0], values3[0], values4[0]);
            var slice0 = _world.ContiguousSlice<C0>(destination[0], _matches[0], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice0[^1], ref destination[^1].Ref<C0>(_matches[0])), "Spawn wave is not contiguous in Component storage.");
            values0.CopyTo(slice0);
            var slice1 = _world.ContiguousSlice<C1>(destination[0], _matches[1], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice1[^1], ref destination[^1].Ref<C1>(_matches[1])), "Spawn wave is not contiguous in Component storage.");
            values1.CopyTo(slice1);
            var slice2 = _world.ContiguousSlice<C2>(destination[0], _matches[2], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice2[^1], ref destination[^1].Ref<C2>(_matches[2])), "Spawn wave is not contiguous in Component storage.");
            values2.CopyTo(slice2);
            var slice3 = _world.ContiguousSlice<C3>(destination[0], _matches[3], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice3[^1], ref destination[^1].Ref<C3>(_matches[3])), "Spawn wave is not contiguous in Component storage.");
            values3.CopyTo(slice3);
            var slice4 = _world.ContiguousSlice<C4>(destination[0], _matches[4], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice4[^1], ref destination[^1].Ref<C4>(_matches[4])), "Spawn wave is not contiguous in Component storage.");
            values4.CopyTo(slice4);
            return this;
        }

        /// <summary>
        /// Spawns <c>count</c> Entities with the configured Components, calling <paramref name="factory"/>
        /// with each Entity's index to produce its required values.
        /// </summary>
        /// <param name="count">number of Entities to spawn</param>
        /// <param name="factory">produces the required values for the Entity at each index</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2, C3, C4> Spawn(int count, Func<int, (C0, C1, C2, C3, C4)> factory)
        {
            AssertMutable();
            ArgumentNullException.ThrowIfNull(factory);
            if (count <= 0) return this;

            var entities = ArrayPool<Entity>.Shared.Rent(count);
            Spawn(entities.AsSpan(0, count), factory);
            ArrayPool<Entity>.Shared.Return(entities);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/>, calling <paramref name="factory"/>
        /// with each Entity's index to produce its required values, and writing the minted handles
        /// into <paramref name="destination"/>.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned</param>
        /// <param name="factory">produces the required values for the Entity at each index</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2, C3, C4> Spawn(Span<Entity> destination, Func<int, (C0, C1, C2, C3, C4)> factory)
        {
            AssertMutable();
            ArgumentNullException.ThrowIfNull(factory);
            if (destination.IsEmpty) return this;

            var count = destination.Length;
            var rented0 = ArrayPool<C0>.Shared.Rent(count);
            var rented1 = ArrayPool<C1>.Shared.Rent(count);
            var rented2 = ArrayPool<C2>.Shared.Rent(count);
            var rented3 = ArrayPool<C3>.Shared.Rent(count);
            var rented4 = ArrayPool<C4>.Shared.Rent(count);
            for (var i = 0; i < count; i++)
            {
                var (c0, c1, c2, c3, c4) = factory(i);
                rented0[i] = c0;
                rented1[i] = c1;
                rented2[i] = c2;
                rented3[i] = c3;
                rented4[i] = c4;
            }
            Spawn(destination, rented0.AsSpan(0, count), rented1.AsSpan(0, count), rented2.AsSpan(0, count), rented3.AsSpan(0, count), rented4.AsSpan(0, count));
            ArrayPool<C0>.Shared.Return(rented0, RuntimeHelpers.IsReferenceOrContainsReferences<C0>());
            ArrayPool<C1>.Shared.Return(rented1, RuntimeHelpers.IsReferenceOrContainsReferences<C1>());
            ArrayPool<C2>.Shared.Return(rented2, RuntimeHelpers.IsReferenceOrContainsReferences<C2>());
            ArrayPool<C3>.Shared.Return(rented3, RuntimeHelpers.IsReferenceOrContainsReferences<C3>());
            ArrayPool<C4>.Shared.Return(rented4, RuntimeHelpers.IsReferenceOrContainsReferences<C4>());
            return this;
        }

        /// <inheritdoc />
        public void Dispose()
        {
            if (_consumed) return; // ownership moved to a wider template via Needs

            ObjectDisposedException.ThrowIf(_disposed, this);
            _disposed = true;

            _components.Dispose();
            _components = null!;

            _values.Dispose();
            _values = null!;
        }
    }

    /// <summary>
    /// An Entity template with 6 required Components, declared via <c>Needs</c>.
    /// Values for the required Components must be provided at <c>Spawn</c>, enforced at compile time.
    /// </summary>
    /// <remarks>
    /// Call any <c>Spawn</c> overload to actually spawn Entities.
    /// </remarks>
    public sealed class EntityTemplate<C0, C1, C2, C3, C4, C5> : IDisposable, IAddRemove<EntityTemplate<C0, C1, C2, C3, C4, C5>>
        where C0 : notnull
        where C1 : notnull
        where C2 : notnull
        where C3 : notnull
        where C4 : notnull
        where C5 : notnull
    {
        #region Internals

        private readonly World _world;

        private PooledList<TypeExpression> _components;
        private PooledList<object> _values;

        // Type Expressions and Match terms of the required Components, index i belongs to Ci.
        private readonly TypeExpression[] _required;
        private readonly Match[] _matches;

        private bool _disposed;

        internal EntityTemplate(World world, PooledList<TypeExpression> components, PooledList<object> values, TypeExpression[] required, Match[] matches)
        {
            _world = world;
            _components = components;
            _values = values;
            _required = required;
            _matches = matches;
        }

        private void AssertMutable() => ObjectDisposedException.ThrowIf(_disposed, this);

        private void AssertNotRequired(TypeExpression type)
        {
            if (Array.IndexOf(_required, type) >= 0)
                throw new InvalidOperationException($"Component {type} is a required Component of this template and must be provided at Spawn.");
        }

        private EntityTemplate<C0, C1, C2, C3, C4, C5> AddComponent(TypeExpression type, object value)
        {
            AssertMutable();
            AssertNotRequired(type);
            if (_components.Contains(type))
            {
                // replace existing value
                _values[_components.IndexOf(type)] = value;
            }
            else
            {
                // add new value
                _components.Add(type);
                _values.Add(value);
            }
            return this;
        }

        private EntityTemplate<C0, C1, C2, C3, C4, C5> RemoveComponent(TypeExpression type)
        {
            AssertMutable();
            AssertNotRequired(type);
            _values.RemoveAt(_components.IndexOf(type));
            _components.Remove(type);
            return this;
        }

        #endregion


        /// <inheritdoc cref="EntityTemplate.Add{T}(T)"/>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Add<T>(T component) where T : notnull
        {
            var type = Comp<T>.Plain.Expression;
            return AddComponent(type, component);
        }

        /// <inheritdoc cref="EntityTemplate.Add{T}(Entity)"/>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Add<T>(Entity target) where T : notnull, new() => Add(new T(), target);


        /// <inheritdoc cref="EntityTemplate.Add{C}()"/>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Add<C>() where C : notnull, new() => Add(new C());


        /// <inheritdoc cref="EntityTemplate.Add{R}(R, Entity)"/>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Add<R>(R value, Entity relation) where R : notnull
        {
            var type = TypeExpression.Of<R>(relation);
            return AddComponent(type, value);
        }


        /// <inheritdoc cref="EntityTemplate.Add{T}(Link{T})"/>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Add<T>(Link<T> target) where T : class
        {
            var type = TypeExpression.Of<T>(target);
            return AddComponent(type, target.Object);
        }


        /// <inheritdoc cref="EntityTemplate.Remove{T}()"/>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Remove<T>() where T : notnull
        {
            var type = Comp<T>.Plain.Expression;
            return RemoveComponent(type);
        }

        /// <inheritdoc cref="EntityTemplate.Remove{T}(Entity)"/>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Remove<T>(Entity entity) where T : notnull
        {
            var type = TypeExpression.Of<T>(entity);
            return RemoveComponent(type);
        }

        /// <inheritdoc cref="EntityTemplate.Remove{L}(L)"/>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Remove<L>(L linkedObject) where L : class => Remove(Link<L>.With(linkedObject));

        /// <inheritdoc cref="EntityTemplate.Remove{L}(Link{L})"/>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Remove<L>(Link<L> link) where L : class
        {
            return RemoveComponent(link.TypeExpression);
        }


        /// <summary>
        /// Spawns a single Entity with the configured Components and the provided required values.
        /// </summary>
        /// <param name="c0">value for the required Component C0</param>
        /// <param name="c1">value for the required Component C1</param>
        /// <param name="c2">value for the required Component C2</param>
        /// <param name="c3">value for the required Component C3</param>
        /// <param name="c4">value for the required Component C4</param>
        /// <param name="c5">value for the required Component C5</param>
        /// <returns>the spawned Entity</returns>
        public Entity Spawn(C0 c0, C1 c1, C2 c2, C3 c3, C4 c4, C5 c5)
        {
            Span<Entity> spawned = stackalloc Entity[1];
            Spawn(spawned, c0, c1, c2, c3, c4, c5);
            return spawned[0];
        }

        /// <summary>
        /// Spawns <c>count</c> Entities with the configured Components; the whole wave shares
        /// the provided required values.
        /// </summary>
        /// <param name="count">number of Entities to spawn</param>
        /// <param name="c0">value for the required Component C0</param>
        /// <param name="c1">value for the required Component C1</param>
        /// <param name="c2">value for the required Component C2</param>
        /// <param name="c3">value for the required Component C3</param>
        /// <param name="c4">value for the required Component C4</param>
        /// <param name="c5">value for the required Component C5</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Spawn(int count, C0 c0, C1 c1, C2 c2, C3 c3, C4 c4, C5 c5)
        {
            AssertMutable();
            if (count <= 0) return this;

            using var components = PooledList<TypeExpression>.Rent();
            using var values = PooledList<object>.Rent();
            components.AddRange(_components);
            values.AddRange(_values);
            components.Add(_required[0]);
            values.Add(c0);
            components.Add(_required[1]);
            values.Add(c1);
            components.Add(_required[2]);
            values.Add(c2);
            components.Add(_required[3]);
            values.Add(c3);
            components.Add(_required[4]);
            values.Add(c4);
            components.Add(_required[5]);
            values.Add(c5);
            _world.Spawn(count, components, values);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/> with the configured
        /// Components, writing their handles into the span; the whole wave shares the provided
        /// required values.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned</param>
        /// <param name="c0">value for the required Component C0</param>
        /// <param name="c1">value for the required Component C1</param>
        /// <param name="c2">value for the required Component C2</param>
        /// <param name="c3">value for the required Component C3</param>
        /// <param name="c4">value for the required Component C4</param>
        /// <param name="c5">value for the required Component C5</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Spawn(Span<Entity> destination, C0 c0, C1 c1, C2 c2, C3 c3, C4 c4, C5 c5)
        {
            AssertMutable();

            using var components = PooledList<TypeExpression>.Rent();
            using var values = PooledList<object>.Rent();
            components.AddRange(_components);
            values.AddRange(_values);
            components.Add(_required[0]);
            values.Add(c0);
            components.Add(_required[1]);
            values.Add(c1);
            components.Add(_required[2]);
            values.Add(c2);
            components.Add(_required[3]);
            values.Add(c3);
            components.Add(_required[4]);
            values.Add(c4);
            components.Add(_required[5]);
            values.Add(c5);
            _world.Spawn(destination, components, values);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/>, taking each Entity's
        /// required values from the value spans at the same index, and writing the minted handles
        /// into <paramref name="destination"/>.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned, and all value spans must match it</param>
        /// <param name="values0">per-Entity values for the required Component C0; length must equal the destination's</param>
        /// <param name="values1">per-Entity values for the required Component C1; length must equal the destination's</param>
        /// <param name="values2">per-Entity values for the required Component C2; length must equal the destination's</param>
        /// <param name="values3">per-Entity values for the required Component C3; length must equal the destination's</param>
        /// <param name="values4">per-Entity values for the required Component C4; length must equal the destination's</param>
        /// <param name="values5">per-Entity values for the required Component C5; length must equal the destination's</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Spawn(Span<Entity> destination, ReadOnlySpan<C0> values0, ReadOnlySpan<C1> values1, ReadOnlySpan<C2> values2, ReadOnlySpan<C3> values3, ReadOnlySpan<C4> values4, ReadOnlySpan<C5> values5)
        {
            AssertMutable();
            if (values0.Length != destination.Length) throw new ArgumentException($"Length ({values0.Length}) must equal destination.Length ({destination.Length})", nameof(values0));
            if (values1.Length != destination.Length) throw new ArgumentException($"Length ({values1.Length}) must equal destination.Length ({destination.Length})", nameof(values1));
            if (values2.Length != destination.Length) throw new ArgumentException($"Length ({values2.Length}) must equal destination.Length ({destination.Length})", nameof(values2));
            if (values3.Length != destination.Length) throw new ArgumentException($"Length ({values3.Length}) must equal destination.Length ({destination.Length})", nameof(values3));
            if (values4.Length != destination.Length) throw new ArgumentException($"Length ({values4.Length}) must equal destination.Length ({destination.Length})", nameof(values4));
            if (values5.Length != destination.Length) throw new ArgumentException($"Length ({values5.Length}) must equal destination.Length ({destination.Length})", nameof(values5));
            if (destination.IsEmpty) return this;

            // Broadcast-spawn the wave (lands contiguously, in destination order, per aspect
            // archetype), then blit each value span straight into its storage slice. (no boxing)
            Spawn(destination, values0[0], values1[0], values2[0], values3[0], values4[0], values5[0]);
            var slice0 = _world.ContiguousSlice<C0>(destination[0], _matches[0], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice0[^1], ref destination[^1].Ref<C0>(_matches[0])), "Spawn wave is not contiguous in Component storage.");
            values0.CopyTo(slice0);
            var slice1 = _world.ContiguousSlice<C1>(destination[0], _matches[1], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice1[^1], ref destination[^1].Ref<C1>(_matches[1])), "Spawn wave is not contiguous in Component storage.");
            values1.CopyTo(slice1);
            var slice2 = _world.ContiguousSlice<C2>(destination[0], _matches[2], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice2[^1], ref destination[^1].Ref<C2>(_matches[2])), "Spawn wave is not contiguous in Component storage.");
            values2.CopyTo(slice2);
            var slice3 = _world.ContiguousSlice<C3>(destination[0], _matches[3], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice3[^1], ref destination[^1].Ref<C3>(_matches[3])), "Spawn wave is not contiguous in Component storage.");
            values3.CopyTo(slice3);
            var slice4 = _world.ContiguousSlice<C4>(destination[0], _matches[4], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice4[^1], ref destination[^1].Ref<C4>(_matches[4])), "Spawn wave is not contiguous in Component storage.");
            values4.CopyTo(slice4);
            var slice5 = _world.ContiguousSlice<C5>(destination[0], _matches[5], destination.Length);
            Debug.Assert(Unsafe.AreSame(ref slice5[^1], ref destination[^1].Ref<C5>(_matches[5])), "Spawn wave is not contiguous in Component storage.");
            values5.CopyTo(slice5);
            return this;
        }

        /// <summary>
        /// Spawns <c>count</c> Entities with the configured Components, calling <paramref name="factory"/>
        /// with each Entity's index to produce its required values.
        /// </summary>
        /// <param name="count">number of Entities to spawn</param>
        /// <param name="factory">produces the required values for the Entity at each index</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Spawn(int count, Func<int, (C0, C1, C2, C3, C4, C5)> factory)
        {
            AssertMutable();
            ArgumentNullException.ThrowIfNull(factory);
            if (count <= 0) return this;

            var entities = ArrayPool<Entity>.Shared.Rent(count);
            Spawn(entities.AsSpan(0, count), factory);
            ArrayPool<Entity>.Shared.Return(entities);
            return this;
        }

        /// <summary>
        /// Spawns one Entity per element of <paramref name="destination"/>, calling <paramref name="factory"/>
        /// with each Entity's index to produce its required values, and writing the minted handles
        /// into <paramref name="destination"/>.
        /// </summary>
        /// <param name="destination">span to fill; its length determines the number of Entities spawned</param>
        /// <param name="factory">produces the required values for the Entity at each index</param>
        /// <returns>itself (fluent interface)</returns>
        public EntityTemplate<C0, C1, C2, C3, C4, C5> Spawn(Span<Entity> destination, Func<int, (C0, C1, C2, C3, C4, C5)> factory)
        {
            AssertMutable();
            ArgumentNullException.ThrowIfNull(factory);
            if (destination.IsEmpty) return this;

            var count = destination.Length;
            var rented0 = ArrayPool<C0>.Shared.Rent(count);
            var rented1 = ArrayPool<C1>.Shared.Rent(count);
            var rented2 = ArrayPool<C2>.Shared.Rent(count);
            var rented3 = ArrayPool<C3>.Shared.Rent(count);
            var rented4 = ArrayPool<C4>.Shared.Rent(count);
            var rented5 = ArrayPool<C5>.Shared.Rent(count);
            for (var i = 0; i < count; i++)
            {
                var (c0, c1, c2, c3, c4, c5) = factory(i);
                rented0[i] = c0;
                rented1[i] = c1;
                rented2[i] = c2;
                rented3[i] = c3;
                rented4[i] = c4;
                rented5[i] = c5;
            }
            Spawn(destination, rented0.AsSpan(0, count), rented1.AsSpan(0, count), rented2.AsSpan(0, count), rented3.AsSpan(0, count), rented4.AsSpan(0, count), rented5.AsSpan(0, count));
            ArrayPool<C0>.Shared.Return(rented0, RuntimeHelpers.IsReferenceOrContainsReferences<C0>());
            ArrayPool<C1>.Shared.Return(rented1, RuntimeHelpers.IsReferenceOrContainsReferences<C1>());
            ArrayPool<C2>.Shared.Return(rented2, RuntimeHelpers.IsReferenceOrContainsReferences<C2>());
            ArrayPool<C3>.Shared.Return(rented3, RuntimeHelpers.IsReferenceOrContainsReferences<C3>());
            ArrayPool<C4>.Shared.Return(rented4, RuntimeHelpers.IsReferenceOrContainsReferences<C4>());
            ArrayPool<C5>.Shared.Return(rented5, RuntimeHelpers.IsReferenceOrContainsReferences<C5>());
            return this;
        }

        /// <inheritdoc />
        public void Dispose()
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            _disposed = true;

            _components.Dispose();
            _components = null!;

            _values.Dispose();
            _values = null!;
        }
    }

}
