//------------------------------------------------------------------------------
// <auto-generated>
//   This file is generated by Stream.Filter.Tests.tt
//   Do not modify directly.
//
//   Regenerate via IDE (Run Custom Tool) or:
//     dotnet tool install -g dotnet-t4
//     t4 Stream.Filter.Tests.tt
//
//   Deliberately no timestamp: regeneration must be diff-clean.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fennecs.tests.Stream;

/// <summary>
/// Generated Stream filter battery: arity 1, Value component set (ValA).
/// </summary>
public class Stream1ValueFilterTests
{
    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void ForFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100)));
        }

        var all = world.Stream<ValA>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.For((ref c0) =>
        {
            top++;
            Assert.True(c0.Value > 50);
        });

        botHalf.For((ref c0) =>
        {
            bot++;
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void JobFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100)));
        }

        var all = world.Stream<ValA>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.Job((ref c0) =>
        {
            Interlocked.Increment(ref top);
            Assert.True(c0.Value > 50);
        });

        botHalf.Job((ref c0) =>
        {
            Interlocked.Increment(ref bot);
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }
}

/// <summary>
/// Generated Stream filter battery: arity 2, Value component set (ValA, ValB).
/// </summary>
public class Stream2ValueFilterTests
{
    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void ForFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(ValB.New(i));
        }

        var all = world.Stream<ValA, ValB>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.For((ref c0, ref _) =>
        {
            top++;
            Assert.True(c0.Value > 50);
        });

        botHalf.For((ref c0, ref _) =>
        {
            bot++;
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void JobFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(ValB.New(i));
        }

        var all = world.Stream<ValA, ValB>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.Job((ref c0, ref _) =>
        {
            Interlocked.Increment(ref top);
            Assert.True(c0.Value > 50);
        });

        botHalf.Job((ref c0, ref _) =>
        {
            Interlocked.Increment(ref bot);
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }
}

/// <summary>
/// Generated Stream filter battery: arity 3, Value component set (ValA, ValB, ValC).
/// </summary>
public class Stream3ValueFilterTests
{
    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void ForFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(ValB.New(i)).Add(ValC.New(i));
        }

        var all = world.Stream<ValA, ValB, ValC>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.For((ref c0, ref _, ref _) =>
        {
            top++;
            Assert.True(c0.Value > 50);
        });

        botHalf.For((ref c0, ref _, ref _) =>
        {
            bot++;
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void JobFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(ValB.New(i)).Add(ValC.New(i));
        }

        var all = world.Stream<ValA, ValB, ValC>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.Job((ref c0, ref _, ref _) =>
        {
            Interlocked.Increment(ref top);
            Assert.True(c0.Value > 50);
        });

        botHalf.Job((ref c0, ref _, ref _) =>
        {
            Interlocked.Increment(ref bot);
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }
}

/// <summary>
/// Generated Stream filter battery: arity 4, Value component set (ValA, ValB, ValC, ValD).
/// </summary>
public class Stream4ValueFilterTests
{
    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void ForFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(ValB.New(i)).Add(ValC.New(i)).Add(ValD.New(i));
        }

        var all = world.Stream<ValA, ValB, ValC, ValD>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.For((ref c0, ref _, ref _, ref _) =>
        {
            top++;
            Assert.True(c0.Value > 50);
        });

        botHalf.For((ref c0, ref _, ref _, ref _) =>
        {
            bot++;
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void JobFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(ValB.New(i)).Add(ValC.New(i)).Add(ValD.New(i));
        }

        var all = world.Stream<ValA, ValB, ValC, ValD>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.Job((ref c0, ref _, ref _, ref _) =>
        {
            Interlocked.Increment(ref top);
            Assert.True(c0.Value > 50);
        });

        botHalf.Job((ref c0, ref _, ref _, ref _) =>
        {
            Interlocked.Increment(ref bot);
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }
}

/// <summary>
/// Generated Stream filter battery: arity 5, Value component set (ValA, ValB, ValC, ValD, ValE).
/// </summary>
public class Stream5ValueFilterTests
{
    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void ForFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(ValB.New(i)).Add(ValC.New(i)).Add(ValD.New(i)).Add(ValE.New(i));
        }

        var all = world.Stream<ValA, ValB, ValC, ValD, ValE>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.For((ref c0, ref _, ref _, ref _, ref _) =>
        {
            top++;
            Assert.True(c0.Value > 50);
        });

        botHalf.For((ref c0, ref _, ref _, ref _, ref _) =>
        {
            bot++;
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void JobFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(ValB.New(i)).Add(ValC.New(i)).Add(ValD.New(i)).Add(ValE.New(i));
        }

        var all = world.Stream<ValA, ValB, ValC, ValD, ValE>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.Job((ref c0, ref _, ref _, ref _, ref _) =>
        {
            Interlocked.Increment(ref top);
            Assert.True(c0.Value > 50);
        });

        botHalf.Job((ref c0, ref _, ref _, ref _, ref _) =>
        {
            Interlocked.Increment(ref bot);
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }
}

/// <summary>
/// Generated Stream filter battery: arity 1, Ref component set (RefA).
/// </summary>
public class Stream1RefFilterTests
{
    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void ForFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(RefA.New(Random.Shared.Next(100)));
        }

        var all = world.Stream<RefA>();

        var topHalf = all.Where((in RefA c) => c.Value > 50);
        var botHalf = all.Where((in RefA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.For((ref c0) =>
        {
            top++;
            Assert.True(c0.Value > 50);
        });

        botHalf.For((ref c0) =>
        {
            bot++;
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void JobFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(RefA.New(Random.Shared.Next(100)));
        }

        var all = world.Stream<RefA>();

        var topHalf = all.Where((in RefA c) => c.Value > 50);
        var botHalf = all.Where((in RefA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.Job((ref c0) =>
        {
            Interlocked.Increment(ref top);
            Assert.True(c0.Value > 50);
        });

        botHalf.Job((ref c0) =>
        {
            Interlocked.Increment(ref bot);
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }
}

/// <summary>
/// Generated Stream filter battery: arity 2, Ref component set (RefA, RefB).
/// </summary>
public class Stream2RefFilterTests
{
    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void ForFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(RefA.New(Random.Shared.Next(100))).Add(RefB.New(i));
        }

        var all = world.Stream<RefA, RefB>();

        var topHalf = all.Where((in RefA c) => c.Value > 50);
        var botHalf = all.Where((in RefA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.For((ref c0, ref _) =>
        {
            top++;
            Assert.True(c0.Value > 50);
        });

        botHalf.For((ref c0, ref _) =>
        {
            bot++;
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void JobFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(RefA.New(Random.Shared.Next(100))).Add(RefB.New(i));
        }

        var all = world.Stream<RefA, RefB>();

        var topHalf = all.Where((in RefA c) => c.Value > 50);
        var botHalf = all.Where((in RefA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.Job((ref c0, ref _) =>
        {
            Interlocked.Increment(ref top);
            Assert.True(c0.Value > 50);
        });

        botHalf.Job((ref c0, ref _) =>
        {
            Interlocked.Increment(ref bot);
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }
}

/// <summary>
/// Generated Stream filter battery: arity 3, Ref component set (RefA, RefB, RefC).
/// </summary>
public class Stream3RefFilterTests
{
    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void ForFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(RefA.New(Random.Shared.Next(100))).Add(RefB.New(i)).Add(RefC.New(i));
        }

        var all = world.Stream<RefA, RefB, RefC>();

        var topHalf = all.Where((in RefA c) => c.Value > 50);
        var botHalf = all.Where((in RefA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.For((ref c0, ref _, ref _) =>
        {
            top++;
            Assert.True(c0.Value > 50);
        });

        botHalf.For((ref c0, ref _, ref _) =>
        {
            bot++;
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void JobFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(RefA.New(Random.Shared.Next(100))).Add(RefB.New(i)).Add(RefC.New(i));
        }

        var all = world.Stream<RefA, RefB, RefC>();

        var topHalf = all.Where((in RefA c) => c.Value > 50);
        var botHalf = all.Where((in RefA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.Job((ref c0, ref _, ref _) =>
        {
            Interlocked.Increment(ref top);
            Assert.True(c0.Value > 50);
        });

        botHalf.Job((ref c0, ref _, ref _) =>
        {
            Interlocked.Increment(ref bot);
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }
}

/// <summary>
/// Generated Stream filter battery: arity 4, Ref component set (RefA, RefB, RefC, RefD).
/// </summary>
public class Stream4RefFilterTests
{
    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void ForFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(RefA.New(Random.Shared.Next(100))).Add(RefB.New(i)).Add(RefC.New(i)).Add(RefD.New(i));
        }

        var all = world.Stream<RefA, RefB, RefC, RefD>();

        var topHalf = all.Where((in RefA c) => c.Value > 50);
        var botHalf = all.Where((in RefA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.For((ref c0, ref _, ref _, ref _) =>
        {
            top++;
            Assert.True(c0.Value > 50);
        });

        botHalf.For((ref c0, ref _, ref _, ref _) =>
        {
            bot++;
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void JobFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(RefA.New(Random.Shared.Next(100))).Add(RefB.New(i)).Add(RefC.New(i)).Add(RefD.New(i));
        }

        var all = world.Stream<RefA, RefB, RefC, RefD>();

        var topHalf = all.Where((in RefA c) => c.Value > 50);
        var botHalf = all.Where((in RefA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.Job((ref c0, ref _, ref _, ref _) =>
        {
            Interlocked.Increment(ref top);
            Assert.True(c0.Value > 50);
        });

        botHalf.Job((ref c0, ref _, ref _, ref _) =>
        {
            Interlocked.Increment(ref bot);
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }
}

/// <summary>
/// Generated Stream filter battery: arity 5, Ref component set (RefA, RefB, RefC, RefD, RefE).
/// </summary>
public class Stream5RefFilterTests
{
    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void ForFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(RefA.New(Random.Shared.Next(100))).Add(RefB.New(i)).Add(RefC.New(i)).Add(RefD.New(i)).Add(RefE.New(i));
        }

        var all = world.Stream<RefA, RefB, RefC, RefD, RefE>();

        var topHalf = all.Where((in RefA c) => c.Value > 50);
        var botHalf = all.Where((in RefA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.For((ref c0, ref _, ref _, ref _, ref _) =>
        {
            top++;
            Assert.True(c0.Value > 50);
        });

        botHalf.For((ref c0, ref _, ref _, ref _, ref _) =>
        {
            bot++;
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void JobFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(RefA.New(Random.Shared.Next(100))).Add(RefB.New(i)).Add(RefC.New(i)).Add(RefD.New(i)).Add(RefE.New(i));
        }

        var all = world.Stream<RefA, RefB, RefC, RefD, RefE>();

        var topHalf = all.Where((in RefA c) => c.Value > 50);
        var botHalf = all.Where((in RefA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.Job((ref c0, ref _, ref _, ref _, ref _) =>
        {
            Interlocked.Increment(ref top);
            Assert.True(c0.Value > 50);
        });

        botHalf.Job((ref c0, ref _, ref _, ref _, ref _) =>
        {
            Interlocked.Increment(ref bot);
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }
}

/// <summary>
/// Generated Stream filter battery: arity 2, Mixed component set (ValA, RefB).
/// </summary>
public class Stream2MixedFilterTests
{
    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void ForFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(RefB.New(i));
        }

        var all = world.Stream<ValA, RefB>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.For((ref c0, ref _) =>
        {
            top++;
            Assert.True(c0.Value > 50);
        });

        botHalf.For((ref c0, ref _) =>
        {
            bot++;
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void JobFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(RefB.New(i));
        }

        var all = world.Stream<ValA, RefB>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.Job((ref c0, ref _) =>
        {
            Interlocked.Increment(ref top);
            Assert.True(c0.Value > 50);
        });

        botHalf.Job((ref c0, ref _) =>
        {
            Interlocked.Increment(ref bot);
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }
}

/// <summary>
/// Generated Stream filter battery: arity 3, Mixed component set (ValA, RefB, ValC).
/// </summary>
public class Stream3MixedFilterTests
{
    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void ForFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(RefB.New(i)).Add(ValC.New(i));
        }

        var all = world.Stream<ValA, RefB, ValC>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.For((ref c0, ref _, ref _) =>
        {
            top++;
            Assert.True(c0.Value > 50);
        });

        botHalf.For((ref c0, ref _, ref _) =>
        {
            bot++;
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void JobFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(RefB.New(i)).Add(ValC.New(i));
        }

        var all = world.Stream<ValA, RefB, ValC>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.Job((ref c0, ref _, ref _) =>
        {
            Interlocked.Increment(ref top);
            Assert.True(c0.Value > 50);
        });

        botHalf.Job((ref c0, ref _, ref _) =>
        {
            Interlocked.Increment(ref bot);
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }
}

/// <summary>
/// Generated Stream filter battery: arity 4, Mixed component set (ValA, RefB, ValC, RefD).
/// </summary>
public class Stream4MixedFilterTests
{
    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void ForFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(RefB.New(i)).Add(ValC.New(i)).Add(RefD.New(i));
        }

        var all = world.Stream<ValA, RefB, ValC, RefD>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.For((ref c0, ref _, ref _, ref _) =>
        {
            top++;
            Assert.True(c0.Value > 50);
        });

        botHalf.For((ref c0, ref _, ref _, ref _) =>
        {
            bot++;
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void JobFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(RefB.New(i)).Add(ValC.New(i)).Add(RefD.New(i));
        }

        var all = world.Stream<ValA, RefB, ValC, RefD>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.Job((ref c0, ref _, ref _, ref _) =>
        {
            Interlocked.Increment(ref top);
            Assert.True(c0.Value > 50);
        });

        botHalf.Job((ref c0, ref _, ref _, ref _) =>
        {
            Interlocked.Increment(ref bot);
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }
}

/// <summary>
/// Generated Stream filter battery: arity 5, Mixed component set (ValA, RefB, ValC, RefD, ValE).
/// </summary>
public class Stream5MixedFilterTests
{
    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void ForFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(RefB.New(i)).Add(ValC.New(i)).Add(RefD.New(i)).Add(ValE.New(i));
        }

        var all = world.Stream<ValA, RefB, ValC, RefD, ValE>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.For((ref c0, ref _, ref _, ref _, ref _) =>
        {
            top++;
            Assert.True(c0.Value > 50);
        });

        botHalf.For((ref c0, ref _, ref _, ref _, ref _) =>
        {
            bot++;
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }

    [Theory]
    [InlineData(0)]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(100)]
    [InlineData(1312)]
    public void JobFilterWithLambda(int count)
    {
        using var world = new World();

        for (var i = 0; i < count; i++)
        {
            world.Spawn().Add(ValA.New(Random.Shared.Next(100))).Add(RefB.New(i)).Add(ValC.New(i)).Add(RefD.New(i)).Add(ValE.New(i));
        }

        var all = world.Stream<ValA, RefB, ValC, RefD, ValE>();

        var topHalf = all.Where((in ValA c) => c.Value > 50);
        var botHalf = all.Where((in ValA c) => c.Value <= 50);

        var top = 0;
        var bot = 0;
        topHalf.Job((ref c0, ref _, ref _, ref _, ref _) =>
        {
            Interlocked.Increment(ref top);
            Assert.True(c0.Value > 50);
        });

        botHalf.Job((ref c0, ref _, ref _, ref _, ref _) =>
        {
            Interlocked.Increment(ref bot);
            Assert.True(c0.Value <= 50);
        });

        Assert.Equal(count, top + bot);
    }
}
